MODULE SURFACE_FUNCTIONS
INTERFACE

SUBROUTINE SURFACE_2D(TYPE1, TYPE2, TIMESTEP, &
           F_POINT_NUM,F_POINT,F_EDGE_NUM,F_EDGE,F_LOC,F_B_RATE,F_PRESSURE,F_BCFLAG, &
           P_POINT_NUM,P_POINT,P_EDGE_NUM,P_EDGE,P_LOC,P_VELOCITY,P_DISPLACEMENT,P_FORCE,P_EDGE_LENGTH,P_CORNER_INDEX, &
           C_POINT_NUM,C_POINT,C_EDGE_NUM,C_EDGE,C_VELOCITY,C_DISPLACEMENT,C_FORCE, &
           FLAG, FLAG_ARRAY, FILENUM, PATCHNUM)
    INTEGER, OPTIONAL :: TYPE1
    INTEGER, OPTIONAL :: TYPE2
    REAL(8), OPTIONAL :: TIMESTEP        
    INTEGER, OPTIONAL :: F_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: F_POINT(:,:)
    INTEGER, OPTIONAL :: F_EDGE_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: F_EDGE(:,:)
    INTEGER, ALLOCATABLE, OPTIONAL :: F_LOC(:)
    INTEGER, OPTIONAL :: F_BCFLAG(:)
    REAL(8), OPTIONAL :: F_B_RATE(:)
    REAL(8), OPTIONAL :: F_PRESSURE(:)
    INTEGER, OPTIONAL :: P_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: P_POINT(:,:)
    INTEGER, OPTIONAL :: P_EDGE_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: P_EDGE(:,:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_LOC(:)
    REAL(8), OPTIONAL :: P_VELOCITY(:,:)
    REAL(8), OPTIONAL :: P_DISPLACEMENT(:,:)
    REAL(8), OPTIONAL :: P_FORCE(:,:)
    REAL(8), ALLOCATABLE, OPTIONAL :: P_EDGE_LENGTH(:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_CORNER_INDEX(:)
    INTEGER, OPTIONAL :: C_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: C_POINT(:,:)
    INTEGER, OPTIONAL :: C_EDGE_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: C_EDGE(:,:)
    REAL(8), OPTIONAL :: C_VELOCITY(:,:)
    REAL(8), OPTIONAL :: C_DISPLACEMENT(:,:)
    REAL(8), OPTIONAL :: C_FORCE(:,:)
    LOGICAL, OPTIONAL :: FLAG
    INTEGER, ALLOCATABLE, OPTIONAL :: FLAG_ARRAY(:)
    INTEGER, OPTIONAL :: FILENUM
    INTEGER, OPTIONAL :: PATCHNUM
END SUBROUTINE SURFACE_2D

SUBROUTINE SURFACE_3D(TYPE1, TYPE2, TIMESTEP, &
           F_POINT_NUM,F_POINT,F_FACE_NUM,F_FACE,F_LOC,F_B_RATE,F_PRESSURE,F_BCFLAG, &
           P_POINT_NUM,P_POINT,P_FACE_NUM,P_FACE,P_LOC,P_VELOCITY,P_DISPLACEMENT,P_FORCE,P_FACE_AREA,P_CORNER_INDEX,P_RIDGE_GROUP_NUM,P_RIDGE_NUM,P_RIDGE, &
           C_POINT_NUM,C_POINT,C_FACE_NUM,C_FACE,C_VELOCITY,C_DISPLACEMENT,C_FORCE, &
           FLAG, FLAG_ARRAY, FILENUM, PATCHNUM)
    INTEGER, OPTIONAL :: TYPE1
    INTEGER, OPTIONAL :: TYPE2
    REAL(8), OPTIONAL :: TIMESTEP
    INTEGER, OPTIONAL :: F_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: F_POINT(:,:)
    INTEGER, OPTIONAL :: F_FACE_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: F_FACE(:,:)
    INTEGER, ALLOCATABLE, OPTIONAL :: F_LOC(:)
    INTEGER, OPTIONAL :: F_BCFLAG(:)
    REAL(8), OPTIONAL :: F_B_RATE(:)
    REAL(8), OPTIONAL :: F_PRESSURE(:)
    INTEGER, OPTIONAL :: P_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: P_POINT(:,:)
    INTEGER, OPTIONAL :: P_FACE_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: P_FACE(:,:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_LOC(:)
    REAL(8), OPTIONAL :: P_VELOCITY(:,:)
    REAL(8), OPTIONAL :: P_DISPLACEMENT(:,:)
    REAL(8), OPTIONAL :: P_FORCE(:,:)
    REAL(8), ALLOCATABLE, OPTIONAL :: P_FACE_AREA(:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_CORNER_INDEX(:)
    INTEGER, OPTIONAL :: P_RIDGE_GROUP_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: P_RIDGE_NUM(:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_RIDGE(:,:)
    INTEGER, OPTIONAL :: C_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: C_POINT(:,:)
    INTEGER, OPTIONAL :: C_FACE_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: C_FACE(:,:)
    REAL(8), OPTIONAL :: C_VELOCITY(:,:)
    REAL(8), OPTIONAL :: C_DISPLACEMENT(:,:)
    REAL(8), OPTIONAL :: C_FORCE(:,:)
    LOGICAL, OPTIONAL :: FLAG
    INTEGER, ALLOCATABLE, OPTIONAL :: FLAG_ARRAY(:)
    INTEGER, OPTIONAL :: FILENUM
    INTEGER, OPTIONAL :: PATCHNUM
END SUBROUTINE SURFACE_3D

END INTERFACE
END MODULE SURFACE_FUNCTIONS

!! THIS SUBROUTINE IS MAIN SUBROUTINE OF SURFACE MODULE

SUBROUTINE SURFACE(DIM, TYPE1, TYPE2, TIMESTEP, &
           F_POINT_NUM,F_POINT,F_ELEMENT_NUM,F_ELEMENT,F_LOC,F_B_RATE,F_PRESSURE,F_BCFLAG, &
           P_POINT_NUM,P_POINT,P_ELEMENT_NUM,P_ELEMENT,P_LOC,P_VELOCITY,P_DISPLACEMENT,P_FORCE,P_ELEMENT_VOLUME,P_CORNER_INDEX,P_RIDGE_GROUP_NUM,P_RIDGE_NUM,P_RIDGE, &
           C_POINT_NUM,C_POINT,C_ELEMENT_NUM,C_ELEMENT,C_VELOCITY,C_DISPLACEMENT,C_FORCE, &
           FLAG, FLAG_ARRAY, FILENUM, PATCHNUM)
    USE SURFACE_FUNCTIONS
    
    INTEGER :: DIM
    
    INTEGER, OPTIONAL :: TYPE1
    INTEGER, OPTIONAL :: TYPE2

    REAL(8), OPTIONAL :: TIMESTEP
        
    INTEGER, OPTIONAL :: F_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: F_POINT(:,:)
    INTEGER, OPTIONAL :: F_ELEMENT_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: F_ELEMENT(:,:)
    INTEGER, ALLOCATABLE, OPTIONAL :: F_LOC(:)
    REAL(8), OPTIONAL :: F_B_RATE(:)
    REAL(8), OPTIONAL :: F_PRESSURE(:)
    INTEGER, OPTIONAL :: F_BCFLAG(:)
        
    INTEGER, OPTIONAL :: P_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: P_POINT(:,:)
    INTEGER, OPTIONAL :: P_ELEMENT_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: P_ELEMENT(:,:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_LOC(:)
    REAL(8), OPTIONAL :: P_VELOCITY(:,:)
    REAL(8), OPTIONAL :: P_DISPLACEMENT(:,:)
    REAL(8), OPTIONAL :: P_FORCE(:,:)
    
    REAL(8), ALLOCATABLE, OPTIONAL :: P_ELEMENT_VOLUME(:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_CORNER_INDEX(:)
    INTEGER, OPTIONAL :: P_RIDGE_GROUP_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: P_RIDGE_NUM(:)
    INTEGER, ALLOCATABLE, OPTIONAL :: P_RIDGE(:,:)
        
    INTEGER, OPTIONAL :: C_POINT_NUM
    REAL(8), ALLOCATABLE, OPTIONAL :: C_POINT(:,:)
    INTEGER, OPTIONAL :: C_ELEMENT_NUM
    INTEGER, ALLOCATABLE, OPTIONAL :: C_ELEMENT(:,:)
    REAL(8), OPTIONAL :: C_VELOCITY(:,:)
    REAL(8), OPTIONAL :: C_DISPLACEMENT(:,:)
    REAL(8), OPTIONAL :: C_FORCE(:,:)
        
    LOGICAL, OPTIONAL :: FLAG
    INTEGER, ALLOCATABLE, OPTIONAL :: FLAG_ARRAY(:)
        
    INTEGER, OPTIONAL :: FILENUM
    INTEGER, OPTIONAL :: PATCHNUM
    
    IF(DIM==2) THEN
        CALL SURFACE_2D(TYPE1, TYPE2, TIMESTEP, &
             F_POINT_NUM,F_POINT,F_ELEMENT_NUM,F_ELEMENT,F_LOC,F_B_RATE,F_PRESSURE,F_BCFLAG, &
             P_POINT_NUM,P_POINT,P_ELEMENT_NUM,P_ELEMENT,P_LOC,P_VELOCITY,P_DISPLACEMENT,P_FORCE,P_ELEMENT_VOLUME,P_CORNER_INDEX, &
             C_POINT_NUM,C_POINT,C_ELEMENT_NUM,C_ELEMENT,C_VELOCITY,C_DISPLACEMENT,C_FORCE, &
             FLAG, FLAG_ARRAY, FILENUM, PATCHNUM)
    ELSE IF(DIM==3) THEN
        CALL SURFACE_3D(TYPE1, TYPE2, TIMESTEP, &
             F_POINT_NUM,F_POINT,F_ELEMENT_NUM,F_ELEMENT,F_LOC,F_B_RATE,F_PRESSURE,F_BCFLAG, &
             P_POINT_NUM,P_POINT,P_ELEMENT_NUM,P_ELEMENT,P_LOC,P_VELOCITY,P_DISPLACEMENT,P_FORCE,P_ELEMENT_VOLUME,P_CORNER_INDEX,P_RIDGE_GROUP_NUM,P_RIDGE_NUM,P_RIDGE, &
             C_POINT_NUM,C_POINT,C_ELEMENT_NUM,C_ELEMENT,C_VELOCITY,C_DISPLACEMENT,C_FORCE, &
             FLAG, FLAG_ARRAY, FILENUM, PATCHNUM)
    END IF
    
END SUBROUTINE SURFACE

