MODULE REMESHING_2D
    USE SURFACE_MODULE_2D
    USE OPERATORS_2D
    USE PROPA_RECONST_REINITIAL_2D
    IMPLICIT NONE

    CONTAINS
    
    !! MODIFIED
    SUBROUTINE CLASSIFY_PATCH(TYP)
        IMPLICIT NONE
        INTEGER :: TYP
        
        REAL(8), ALLOCATABLE :: NEWPOINT(:,:) 
        INTEGER, ALLOCATABLE :: NEWEDGE(:,:)
        
        REAL(8), ALLOCATABLE :: SURFACE_INITIAL_EDGE_LENGTH(:)
        REAL(8), ALLOCATABLE :: EDGE_B_RATE(:)
        REAL(8), ALLOCATABLE :: POINT_VELOCITY(:,:)
        REAL(8), ALLOCATABLE :: POINT_DISPLACEMENT(:,:)
        INTEGER, ALLOCATABLE :: POINT_EDGE_CONNECTION(:,:)
        INTEGER, ALLOCATABLE :: POINT_TYPE(:)
        INTEGER, ALLOCATABLE :: EDGE_LOCATION(:)
        INTEGER, ALLOCATABLE :: EDGE_ONINTERFACE(:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDPT(:,:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDEDGE(:,:)
        REAL(8), ALLOCATABLE :: EDGE_PRESSURE(:)
        REAL(8), ALLOCATABLE :: POINT_FORCE(:,:)
        INTEGER, ALLOCATABLE :: EDGE_IMPACT_ZONE(:,:)
	INTEGER, ALLOCATABLE :: EDGE_ABLATION_FLAG(:)
        
        INTEGER :: PATCH_NUM
        INTEGER :: TEMP
        
        INTEGER :: I,J
        
        INTEGER, ALLOCATABLE :: POINT_INDEX(:)
        INTEGER, ALLOCATABLE :: EDGE_INDEX(:)
        
        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF
        
        ALLOCATE(NEWPOINT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(NEWEDGE(2,SURFACE_CURRENT%SURFACE_EDGES_NUM))
        
        ALLOCATE(POINT_INDEX(SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(EDGE_INDEX(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        
        ALLOCATE(SURFACE_INITIAL_EDGE_LENGTH(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_B_RATE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(POINT_VELOCITY(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_DISPLACEMENT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_EDGE_CONNECTION(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_TYPE(SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(EDGE_LOCATION(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_ONINTERFACE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(POINT_RELATEDPT(3,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_RELATEDEDGE(3,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(EDGE_PRESSURE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(POINT_FORCE(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(EDGE_IMPACT_ZONE(3,SURFACE_CURRENT%SURFACE_EDGES_NUM))
	    ALLOCATE(EDGE_ABLATION_FLAG(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        
        PATCH_NUM = 1 
        TEMP = 0
        
        DO WHILE(TEMP < SURFACE_CURRENT%SURFACE_POINTS_NUM)
            DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,I))==PATCH_NUM) THEN
                    TEMP = TEMP+1
                    NEWPOINT(:,TEMP) = SURFACE_CURRENT%SURFACE_POINTS(:,I)
                    POINT_INDEX(I) = TEMP
                END IF
            END DO
            PATCH_NUM = PATCH_NUM + 1
        END DO
        
        SURFACE_CURRENT%SURFACE_POINTS(:,:) = NEWPOINT(:,:)
        
        DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
            SURFACE_CURRENT%SURFACE_EDGES(:,J) = POINT_INDEX(SURFACE_CURRENT%SURFACE_EDGES(:,J))
        END DO
        
        PATCH_NUM = 1
        TEMP = 0
        
        DO WHILE(TEMP < SURFACE_CURRENT%SURFACE_EDGES_NUM)
            DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(J)==PATCH_NUM) THEN
                    TEMP = TEMP+1                       
                    NEWEDGE(:,TEMP) = SURFACE_CURRENT%SURFACE_EDGES(:,J)
                    EDGE_INDEX(J) = TEMP
                END IF
            END DO
            PATCH_NUM = PATCH_NUM + 1
        END DO
        
        SURFACE_CURRENT%SURFACE_EDGES(:,:) = NEWEDGE(:,:)
        
        DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            POINT_VELOCITY(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_VELOCITY(:,I)
            POINT_DISPLACEMENT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_DISPLACEMENT(:,I)
            POINT_EDGE_CONNECTION(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,I)
            POINT_TYPE(POINT_INDEX(I)) = SURFACE_CURRENT%POINT_TYPE(I)
            POINT_RELATEDPT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDPT(:,I)
            POINT_RELATEDEDGE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDEDGE(:,I)
            POINT_FORCE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_FORCE(:,I)
        END DO
        
        DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
            SURFACE_INITIAL_EDGE_LENGTH(EDGE_INDEX(J)) = SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J)
            EDGE_B_RATE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_B_RATE(J)
            EDGE_LOCATION(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_LOCATION(J)
            EDGE_ONINTERFACE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ONINTERFACE(J)
            EDGE_PRESSURE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_PRESSURE(J)
            EDGE_IMPACT_ZONE(:,EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_IMPACT_ZONE(:,J)
	    EDGE_ABLATION_FLAG(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ABLATION_FLAG(J)
        END DO
        
        DO J = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            POINT_EDGE_CONNECTION(:,J) = EDGE_INDEX(POINT_EDGE_CONNECTION(:,J))
        END DO
        
        SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(:) = SURFACE_INITIAL_EDGE_LENGTH(:)
        SURFACE_CURRENT%EDGE_B_RATE(:) = EDGE_B_RATE(:)
        SURFACE_CURRENT%POINT_VELOCITY(:,:) = POINT_VELOCITY(:,:)
        SURFACE_CURRENT%POINT_DISPLACEMENT(:,:) = POINT_DISPLACEMENT(:,:)
        SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,:) = POINT_EDGE_CONNECTION(:,:)
        SURFACE_CURRENT%POINT_TYPE(:) = POINT_TYPE(:)
        SURFACE_CURRENT%EDGE_LOCATION(:) = EDGE_LOCATION(:)
        SURFACE_CURRENT%EDGE_ONINTERFACE(:) = EDGE_ONINTERFACE(:)
        SURFACE_CURRENT%POINT_RELATEDPT(:,:) = POINT_RELATEDPT(:,:)
        SURFACE_CURRENT%POINT_RELATEDEDGE(:,:) = POINT_RELATEDEDGE(:,:)
        SURFACE_CURRENT%EDGE_PRESSURE(:) = EDGE_PRESSURE(:)
        SURFACE_CURRENT%POINT_FORCE(:,:) = POINT_FORCE(:,:)
        SURFACE_CURRENT%EDGE_IMPACT_ZONE(:,:) = EDGE_IMPACT_ZONE(:,:)
        SURFACE_CURRENT%EDGE_ABLATION_FLAG(:) = EDGE_ABLATION_FLAG(:)
        
        DEALLOCATE(SURFACE_INITIAL_EDGE_LENGTH)
        DEALLOCATE(EDGE_B_RATE)
        DEALLOCATE(POINT_VELOCITY)
        DEALLOCATE(POINT_DISPLACEMENT)
        DEALLOCATE(POINT_EDGE_CONNECTION)
        DEALLOCATE(POINT_TYPE)
        DEALLOCATE(EDGE_LOCATION)
        DEALLOCATE(EDGE_ONINTERFACE)
        DEALLOCATE(POINT_RELATEDPT)
        DEALLOCATE(POINT_RELATEDEDGE)
        DEALLOCATE(EDGE_PRESSURE)
        DEALLOCATE(POINT_FORCE)
        DEALLOCATE(EDGE_IMPACT_ZONE)
        DEALLOCATE(EDGE_ABLATION_FLAG)
        
        DEALLOCATE(EDGE_INDEX)
        DEALLOCATE(POINT_INDEX)
        
        DEALLOCATE(NEWEDGE)
        DEALLOCATE(NEWPOINT)
        
    END SUBROUTINE CLASSIFY_PATCH

    SUBROUTINE NEW_POINTEDGE_INDEX(TYP, NEWPOINT_NUM, NEWPOINT, NEWEDGE_NUM, NEWEDGE, POINT_INDEX, EDGE_INDEX) !NEW_PATCH_NUM)!, NEW_PATCH_ZIPPER_TYPE)
        IMPLICIT NONE
        INTEGER :: TYP
        
        INTEGER :: NEWPOINT_NUM, NEWEDGE_NUM
        
        REAL(8) :: NEWPOINT(2,NEWPOINT_NUM) 
        INTEGER :: NEWEDGE(2,NEWEDGE_NUM)
       	!INTEGER :: NEW_PATCH_NUM
        INTEGER :: POINT_INDEX(:)
        INTEGER :: EDGE_INDEX(:)
        
        INTEGER :: I,J
	!INTEGER :: NEW_PATCH_ZIPPER_TYPE(NEW_PATCH_NUM)        

        REAL(8), ALLOCATABLE :: SURFACE_INITIAL_EDGE_LENGTH(:)
        REAL(8), ALLOCATABLE :: EDGE_B_RATE(:)
        REAL(8), ALLOCATABLE :: POINT_VELOCITY(:,:)
        REAL(8), ALLOCATABLE :: POINT_DISPLACEMENT(:,:)
        INTEGER, ALLOCATABLE :: POINT_EDGE_CONNECTION(:,:)
        INTEGER, ALLOCATABLE :: POINT_TYPE(:)
        INTEGER, ALLOCATABLE :: EDGE_LOCATION(:)
        INTEGER, ALLOCATABLE :: EDGE_ONINTERFACE(:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDPT(:,:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDEDGE(:,:)
        REAL(8), ALLOCATABLE :: EDGE_PRESSURE(:)
        REAL(8), ALLOCATABLE :: POINT_FORCE(:,:)
        INTEGER, ALLOCATABLE :: EDGE_IMPACT_ZONE(:,:)
	INTEGER, ALLOCATABLE :: EDGE_ABLATION_FLAG(:)
        
        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF
        
        ALLOCATE(SURFACE_INITIAL_EDGE_LENGTH(NEWEDGE_NUM))
        ALLOCATE(EDGE_B_RATE(NEWEDGE_NUM))
        ALLOCATE(POINT_VELOCITY(2,NEWPOINT_NUM))
        ALLOCATE(POINT_DISPLACEMENT(2,NEWPOINT_NUM))
        ALLOCATE(POINT_EDGE_CONNECTION(2,NEWPOINT_NUM))
        ALLOCATE(POINT_TYPE(NEWPOINT_NUM))
        ALLOCATE(EDGE_LOCATION(NEWEDGE_NUM))
        ALLOCATE(EDGE_ONINTERFACE(NEWEDGE_NUM))
        ALLOCATE(POINT_RELATEDPT(3,NEWPOINT_NUM))
        ALLOCATE(POINT_RELATEDEDGE(3,NEWPOINT_NUM))
        ALLOCATE(EDGE_PRESSURE(NEWEDGE_NUM))
        ALLOCATE(POINT_FORCE(2,NEWPOINT_NUM))
        ALLOCATE(EDGE_IMPACT_ZONE(3,NEWEDGE_NUM))
        ALLOCATE(EDGE_ABLATION_FLAG(NEWEDGE_NUM))

        DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            IF(POINT_INDEX(I).NE.0) THEN
                POINT_VELOCITY(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_VELOCITY(:,I)
                POINT_DISPLACEMENT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_DISPLACEMENT(:,I)
                POINT_EDGE_CONNECTION(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,I)
                POINT_TYPE(POINT_INDEX(I)) = SURFACE_CURRENT%POINT_TYPE(I)
                POINT_RELATEDPT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDPT(:,I)
                POINT_RELATEDEDGE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDEDGE(:,I)
                POINT_FORCE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_FORCE(:,I)
            END IF
        END DO
        
        DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
            IF(EDGE_INDEX(J).NE.0) THEN
                SURFACE_INITIAL_EDGE_LENGTH(EDGE_INDEX(J)) = SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J)
                EDGE_B_RATE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_B_RATE(J)
                EDGE_LOCATION(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_LOCATION(J)
                EDGE_ONINTERFACE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ONINTERFACE(J)
                EDGE_PRESSURE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_PRESSURE(J)
                EDGE_IMPACT_ZONE(:,EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_IMPACT_ZONE(:,J)
		EDGE_ABLATION_FLAG(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ABLATION_FLAG(J)
            END IF
        END DO
        
        DO J = 1, NEWEDGE_NUM
            NEWEDGE(:,J) = POINT_INDEX(NEWEDGE(:,J))
        END DO
        
        DO J = 1, NEWPOINT_NUM
            POINT_EDGE_CONNECTION(:,J) = EDGE_INDEX(POINT_EDGE_CONNECTION(:,J))
        END DO
        
        CALL RESET_SURFACE(TYP, .TRUE., NEWPOINT_NUM, NEWEDGE_NUM, NEWPOINT, NEWEDGE, &
             SURFACE_INITIAL_EDGE_LENGTH, EDGE_B_RATE, POINT_VELOCITY, POINT_DISPLACEMENT, &
             POINT_EDGE_CONNECTION, POINT_TYPE, EDGE_LOCATION, EDGE_ONINTERFACE, POINT_RELATEDPT, POINT_RELATEDEDGE, EDGE_PRESSURE, POINT_FORCE, EDGE_IMPACT_ZONE, EDGE_ABLATION_FLAG)
	!SURFACE_CURRENT%SURFACE_PATCHES_NUM = NEW_PATCH_NUM
        
        DEALLOCATE(SURFACE_INITIAL_EDGE_LENGTH)
        DEALLOCATE(EDGE_B_RATE)
        DEALLOCATE(POINT_VELOCITY)
        DEALLOCATE(POINT_DISPLACEMENT)
        DEALLOCATE(POINT_EDGE_CONNECTION)
        DEALLOCATE(POINT_TYPE)
        DEALLOCATE(EDGE_LOCATION)
        DEALLOCATE(EDGE_ONINTERFACE)
        DEALLOCATE(POINT_RELATEDPT)
        DEALLOCATE(POINT_RELATEDEDGE)
        DEALLOCATE(EDGE_PRESSURE)
        DEALLOCATE(POINT_FORCE)
        DEALLOCATE(EDGE_IMPACT_ZONE)
        DEALLOCATE(EDGE_ABLATION_FLAG)

    END SUBROUTINE NEW_POINTEDGE_INDEX

    !! END MODIFIED
    
    SUBROUTINE ATTACH_TWO_EDGES(TYP, I1, I2)
	IMPLICIT NONE
        INTEGER :: TYP
        INTEGER :: I1, I2, J1, J2
	INTEGER :: POINT_IDX1,POINT_IDX2,POINT_IDX3,POINT_IDX4
        REAL(8) :: R
        
        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF
        
        POINT_IDX1 = SURFACE_CURRENT%SURFACE_EDGES(1,I1)
        POINT_IDX2 = SURFACE_CURRENT%SURFACE_EDGES(2,I1)
        
        POINT_IDX3 = SURFACE_CURRENT%SURFACE_EDGES(1,I2)
        POINT_IDX4 = SURFACE_CURRENT%SURFACE_EDGES(2,I2)
        
        SURFACE_CURRENT%SURFACE_EDGES(1,I1) = POINT_IDX1
        SURFACE_CURRENT%SURFACE_EDGES(2,I1) = POINT_IDX4
        
        SURFACE_CURRENT%SURFACE_EDGES(1,I2) = POINT_IDX3
        SURFACE_CURRENT%SURFACE_EDGES(2,I2) = POINT_IDX2
        
        SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,POINT_IDX4) = I1
        SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,POINT_IDX2) = I2

	SURFACE_CURRENT%POINT_TYPE(POINT_IDX1) = 2
	SURFACE_CURRENT%POINT_TYPE(POINT_IDX2) = 2
	SURFACE_CURRENT%POINT_TYPE(POINT_IDX3) = 2
	SURFACE_CURRENT%POINT_TYPE(POINT_IDX4) = 2

	!SURFACE_CURRENT%EDGE_ZIPPER_FLAG(I1) = .TRUE.
	!SURFACE_CURRENT%EDGE_ZIPPER_FLAG(I2) = .TRUE.
        
        SURFACE_CURRENT%EDGE_ONINTERFACE(I1) = -1
        SURFACE_CURRENT%EDGE_ONINTERFACE(I2) = -1

        J1 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,POINT_IDX1)
        J2 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,POINT_IDX4)
        
        R = (SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J1) + SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J2))/2.
        SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(I1) = R
        
        J1 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,POINT_IDX2)
        J2 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,POINT_IDX3)
        
        R = (SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J1) + SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J2))/2.
        SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(I2) = R
        
    END SUBROUTINE ATTACH_TWO_EDGES
    
SUBROUTINE REMOVE_SMALL_REGIONS(TYP, PATCH_BEFORE_INDEX, PATCH_PARENT, FLAG)
        IMPLICIT NONE
        INTEGER :: TYP
        INTEGER :: I, J, I2, J2, NUM
	INTEGER :: ITER, CURRENT_EDGE, INITIAL_EDGE, REGION_NUM
	INTEGER, ALLOCATABLE :: INITIAL_CURRENT_EDGES(:), PATCH_ZIPPER_TYPE(:), PATCH_INDEX(:)
	INTEGER, ALLOCATABLE :: PATCH_BEFORE_INDEX(:)
	INTEGER, ALLOCATABLE, OPTIONAL :: PATCH_PARENT(:)
	LOGICAL :: B, TEMPFLAG
	LOGICAL, OPTIONAL :: FLAG
        
	LOGICAL, ALLOCATABLE :: REMOVE_REGIONS(:)
	INTEGER :: PATCH_NUM
	INTEGER :: NUM_NONZERO_INDEX, NUM_ZERO_INDEX
        
        INTEGER :: NEWPOINT_NUM, NEWEDGE_NUM, NEWPATCH_NUM
        
        REAL(8), ALLOCATABLE :: NEWPOINT(:,:) 
        INTEGER, ALLOCATABLE :: NEWEDGE(:,:)
        
        INTEGER, ALLOCATABLE :: POINT_INDEX(:)
        INTEGER, ALLOCATABLE :: EDGE_INDEX(:)

        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF
        
        ALLOCATE(INITIAL_CURRENT_EDGES(100))
        PATCH_NUM = 0
        B = .TRUE.
        DO WHILE(B)
            B = .FALSE.
            DO I = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(I)==PATCH_NUM + 1) THEN
                    PATCH_NUM = PATCH_NUM + 1
                    INITIAL_CURRENT_EDGES(PATCH_NUM) = I
                    B = .TRUE.
                    EXIT
                END IF
            END DO
        END DO
        
        ALLOCATE(REMOVE_REGIONS(PATCH_NUM))
        REMOVE_REGIONS(:) = .FALSE.
        DO ITER = 1, PATCH_NUM
            CURRENT_EDGE = INITIAL_CURRENT_EDGES(ITER)
            
            INITIAL_EDGE = CURRENT_EDGE
            
            B = .TRUE.
            REGION_NUM = 0
            
            DO WHILE(B)
                
                J2 = SURFACE_CURRENT%SURFACE_EDGES(2,CURRENT_EDGE)
                I2 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,J2)
                CURRENT_EDGE = I2
                REGION_NUM = REGION_NUM + 1
                
                IF(CURRENT_EDGE==INITIAL_EDGE) THEN
                    B = .FALSE.
                END IF
            END DO
            
            IF(REGION_NUM<10) THEN
                REMOVE_REGIONS(ITER) = .TRUE.
            END IF
        END DO
        
        ALLOCATE(NEWPOINT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(NEWEDGE(2,SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(POINT_INDEX(SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(EDGE_INDEX(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        
        POINT_INDEX(:) = 0
        EDGE_INDEX(:) = 0
        
        NEWPOINT_NUM = 0
        B = .TRUE.
        ITER = 1
        
        DO WHILE(B)
            B = .FALSE.
            DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,I))==ITER) THEN
                    B = .TRUE.
                    IF(.NOT. REMOVE_REGIONS(ITER)) THEN
                        NEWPOINT_NUM = NEWPOINT_NUM+1
                        NEWPOINT(:,NEWPOINT_NUM) = SURFACE_CURRENT%SURFACE_POINTS(:,I)
                        POINT_INDEX(I) = NEWPOINT_NUM
                    END IF
                END IF
            END DO
            ITER = ITER + 1
        END DO
        
        NEWEDGE_NUM = 0
        B = .TRUE.
        ITER = 1
        
        DO WHILE(B)
            B = .FALSE.
            DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(J)==ITER) THEN
                    B = .TRUE.
                    IF(.NOT. REMOVE_REGIONS(ITER)) THEN
                        NEWEDGE_NUM = NEWEDGE_NUM+1
                        NEWEDGE(:,NEWEDGE_NUM) = SURFACE_CURRENT%SURFACE_EDGES(:,J)
                        EDGE_INDEX(J) = NEWEDGE_NUM
                    END IF
                END IF
            END DO
            ITER = ITER + 1
        END DO

	NEWPATCH_NUM = 0
	B = .TRUE.

	IF(ALLOCATED(PATCH_INDEX)) THEN
	    DEALLOCATE(PATCH_INDEX)
	END IF

	ALLOCATE(PATCH_INDEX(PATCH_NUM))
	PATCH_INDEX(:) = 0

        DO I = 1, PATCH_NUM
           IF(.NOT. REMOVE_REGIONS(I)) THEN
               NEWPATCH_NUM = NEWPATCH_NUM+1
               PATCH_INDEX(I) = NEWPATCH_NUM
           END IF
        END DO

	IF(ALLOCATED(PATCH_ZIPPER_TYPE)) THEN
	    DEALLOCATE(PATCH_ZIPPER_TYPE)
	END IF

	

	NUM = 0
        DO I=1, PATCH_NUM
           IF(PATCH_INDEX(I) .NE. 0) THEN
	      NUM = NUM +1
           END IF
        END DO

        IF(ALLOCATED(PATCH_PARENT)) THEN
	    DEALLOCATE(PATCH_PARENT)
	END IF
	    ALLOCATE(PATCH_PARENT(NUM))

	DO I=1,PATCH_NUM
	   IF(PATCH_INDEX(I) .NE. 0) THEN
		PATCH_PARENT(PATCH_INDEX(I)) = PATCH_BEFORE_INDEX(I)
	   END IF
	END DO

	CALL NEW_POINTEDGE_INDEX(TYP, NEWPOINT_NUM, NEWPOINT, NEWEDGE_NUM, NEWEDGE, POINT_INDEX, EDGE_INDEX)

	ALLOCATE(PATCH_ZIPPER_TYPE(PATCH_NUM))
	PATCH_ZIPPER_TYPE(:) = 0
	TEMPFLAG = .FALSE.

IF(FLAG) THEN
WRITE(*,*) 'TOP CHANGE!'
END IF

!	DO I=1,PATCH_NUM
!	   TEMPFLAG = .FALSE.
!          DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
!	      J0 = SURFACE_CURRENT%EDGE_LOCATION(J)
!	      IF(J0 .EQ. I .AND. PATCH_INDEX(J0) .NE. 0) THEN
!	          TEMPFLAG = .TRUE.   
!	          EXIT
!	      END IF	
!           END DO
	
!	   IF(TEMPFLAG .AND. .NOT. FLAG) THEN
!	       PATCH_ZIPPER_TYPE(I) = 0
!	   ELSE IF(TEMPFLAG .AND. FLAG) THEN
!	       PATCH_ZIPPER_TYPE(I) = 2
!	   ELSE
!	       PATCH_ZIPPER_TYPE(I) = 3
!	   END IF
!	END DO

!	IF(ALLOCATED(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP)) THEN
!	    DEALLOCATE(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP)
!	END IF

!	CALL FIND_PATCH_NUM(1)

!       ALLOCATE(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(SURFACE_PROPEL%SURFACE_PATCHES_NUM))

	DO I=1,SURFACE_PROPEL%SURFACE_PATCHES_NUM
		NUM_ZERO_INDEX = 0
		NUM_NONZERO_INDEX = 0

		DO J=1,PATCH_NUM
			IF(PATCH_BEFORE_INDEX(J) .EQ. I) THEN
				IF(PATCH_INDEX(J) == 0) THEN
					NUM_ZERO_INDEX = NUM_ZERO_INDEX + 1
				ELSE   
					NUM_NONZERO_INDEX = NUM_NONZERO_INDEX +1
				END IF
			END IF
		END DO	
   
		IF(NUM_NONZERO_INDEX .EQ. 1 .AND. NUM_ZERO_INDEX .EQ. 0 .AND. SURFACE_PROPEL%SURFACE_PATCHES_TOPCHANGE_TYP(I) .NE. 11) THEN
			SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(I) = 0
		ELSE IF(NUM_NONZERO_INDEX .EQ. 1 .AND. NUM_ZERO_INDEX .GT. 0) THEN
			SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(I) = 2
		ELSE IF(NUM_NONZERO_INDEX .EQ. 0) THEN
			SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(I) = 3		
		ELSE IF(NUM_NONZERO_INDEX .GE. 2) THEN
			SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(I) = 4
		ELSE
			WRITE(*,*) 'TOPCHANGE_TYP ERROR!'
			SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(10000) = -1
		END IF 	

	END DO



   	!DO I=1,PATCH_NUM
        !   IF(PATCH_INDEX(I) .NE. 0) THEN
	!	SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(PATCH_INDEX(I)) = PATCH_ZIPPER_TYPE(I)
        !   END IF
	!END DO         

	SURFACE_PROPEL%SURFACE_PATCHES_NUM = NUM

        CALL RESET_PATCH(TYP)
        
        DEALLOCATE(NEWPOINT)
        DEALLOCATE(NEWEDGE)
        DEALLOCATE(POINT_INDEX)
        DEALLOCATE(EDGE_INDEX)
	DEALLOCATE(REMOVE_REGIONS)
	DEALLOCATE(INITIAL_CURRENT_EDGES)
	DEALLOCATE(PATCH_ZIPPER_TYPE)
	DEALLOCATE(PATCH_INDEX)
	DEALLOCATE(PATCH_BEFORE_INDEX)
	DEALLOCATE(PATCH_PARENT)

    END SUBROUTINE REMOVE_SMALL_REGIONS

   ! SUBROUTINE RENEW_SURFACE_INFORMATION(TYP)

   !     INTEGER :: TYP

   !     TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
   !     IF (TYP==0) THEN
   !         SURFACE_CURRENT => SURFACE_FLUID
   !     END IF
   !     IF (TYP==1) THEN
   !         SURFACE_CURRENT => SURFACE_PROPEL
   !     END IF
   !     IF (TYP==2) THEN
   !         SURFACE_CURRENT => SURFACE_CASE
   !     END IF

!	IF(TYP .EQ. 1) THEN
!	   DO I=1,SURFACE_FLUID%SURFACE_POINTS_NUM
!	      J = SURFACE_FLUID%POINT_RELATEDPT(1+1,I)
!	      IF(J .NE. 0) THEN
! 	          IF(SURFACE_FLUID%POINT_TYPE(I) .EQ. 3 .AND. POINT_INDEX(J) .EQ. 0) THEN
!		      SURFACE_FLUID%POINT_TYPE(I) = 2
!	          END IF
!	      END IF
!	   END DO
!         END IF

!    END SUBROUTINE
    
!    SUBROUTINE REMOVE_LARGE_REGION(TYP, REGION_NUM)
        
!        INTEGER :: TYP
!        INTEGER :: I, J
!	INTEGER :: ITER, REGION_NUM
!	LOGICAL :: B
        
!        INTEGER :: NEWPOINT_NUM, NEWEDGE_NUM
        
!        REAL(8), ALLOCATABLE :: NEWPOINT(:,:) 
!        INTEGER, ALLOCATABLE :: NEWEDGE(:,:)
        
!        INTEGER, ALLOCATABLE :: POINT_INDEX(:)
!        INTEGER, ALLOCATABLE :: EDGE_INDEX(:)

!        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
!        IF (TYP==0) THEN
!            SURFACE_CURRENT => SURFACE_FLUID
!        END IF
!        IF (TYP==1) THEN
!            SURFACE_CURRENT => SURFACE_PROPEL
!        END IF
!       IF (TYP==2) THEN
!            SURFACE_CURRENT => SURFACE_CASE
!        END IF
        
!        ALLOCATE(NEWPOINT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
!        ALLOCATE(NEWEDGE(2,SURFACE_CURRENT%SURFACE_EDGES_NUM))
!        ALLOCATE(POINT_INDEX(SURFACE_CURRENT%SURFACE_POINTS_NUM))
!        ALLOCATE(EDGE_INDEX(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        
!        POINT_INDEX(:) = 0
!        EDGE_INDEX(:) = 0
        
!        NEWPOINT_NUM = 0
!        B = .TRUE.
!        ITER = 1
        
!        DO WHILE(B)
!            B = .FALSE.
!            DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
!                IF(SURFACE_CURRENT%EDGE_LOCATION(SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,I))==ITER) THEN
!                    B = .TRUE.
!                    IF(ITER .NE. REGION_NUM) THEN
!                        NEWPOINT_NUM = NEWPOINT_NUM+1
!                        NEWPOINT(:,NEWPOINT_NUM) = SURFACE_CURRENT%SURFACE_POINTS(:,I)
!                        POINT_INDEX(I) = NEWPOINT_NUM
!                    END IF
!                END IF
!            END DO
!            ITER = ITER + 1
!        END DO
        
!        NEWEDGE_NUM = 0
!        B = .TRUE.
!        ITER = 1
        
!        DO WHILE(B)
!            B = .FALSE.
!            DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
!                IF(SURFACE_CURRENT%EDGE_LOCATION(J)==ITER) THEN
!                    B = .TRUE.
!                    IF(ITER .NE. REGION_NUM) THEN
!                        NEWEDGE_NUM = NEWEDGE_NUM+1
!                        NEWEDGE(:,NEWEDGE_NUM) = SURFACE_CURRENT%SURFACE_EDGES(:,J)
!                        EDGE_INDEX(J) = NEWEDGE_NUM
!                    END IF
!                END IF
!            END DO
!            ITER = ITER + 1
!        END DO
        
!        write(*,*) 'NEWPOINT NUM', NEWPOINT_NUM
!        write(*,*) 'NEWEDGE NUM', NEWEDGE_NUM
        
!        CALL NEW_POINTEDGE_INDEX(TYP, NEWPOINT_NUM, NEWPOINT, NEWEDGE_NUM, NEWEDGE, POINT_INDEX, EDGE_INDEX)
        
!        DEALLOCATE(NEWPOINT)
!        DEALLOCATE(NEWEDGE)
!        DEALLOCATE(POINT_INDEX)
!        DEALLOCATE(EDGE_INDEX)
        
!        CALL RESET_PATCH(TYP, PATCH_PARENT)
        
!    END SUBROUTINE REMOVE_LARGE_REGION
    
    SUBROUTINE RESET_PATCH(TYP, PATCH_BEFORE_INDEX) !, PATCH_PARENT, TEMP_PATCH_NUM, PATCH_INDEX, PATCH_ZIPPER_TYPE, FLAG)
        IMPLICIT NONE
        INTEGER :: TYP
        INTEGER :: I2, J2, J
	!INTEGER, OPTIONAL :: TEMP_PATCH_NUM
	INTEGER :: I, PATCH_NUM, CURRENT_EDGE, INITIAL_EDGE, TEMP
	!INTEGER, ALLOCATABLE, OPTIONAL :: PATCH_PARENT(:)
	!INTEGER, ALLOCATABLE, OPTIONAL :: PATCH_INDEX(:)
	INTEGER, ALLOCATABLE, OPTIONAL :: PATCH_BEFORE_INDEX(:)
	!INTEGER, ALLOCATABLE, OPTIONAL :: PATCH_ZIPPER_TYPE(:)
	!LOGICAL, OPTIONAL :: FLAG
	LOGICAL :: B
        LOGICAL, ALLOCATABLE :: USED_EDGE(:)
	INTEGER, ALLOCATABLE :: TEMP_LOCATION(:)
        
        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF

	!IF(.NOT. PRESENT(PATCH_PARENT)) THEN
        
        ALLOCATE(USED_EDGE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        USED_EDGE(:) = .FALSE.
        ALLOCATE(TEMP_LOCATION(SURFACE_CURRENT%SURFACE_EDGES_NUM))
	TEMP_LOCATION(:) = 0
	IF(PRESENT(PATCH_BEFORE_INDEX)) THEN
           ALLOCATE(PATCH_BEFORE_INDEX(SURFACE_CURRENT%SURFACE_EDGES_NUM))
	   PATCH_BEFORE_INDEX(:) = 0	
	END IF
        
        PATCH_NUM = 1
        TEMP = 0
        DO WHILE(TEMP < SURFACE_CURRENT%SURFACE_EDGES_NUM)
            DO I=1,SURFACE_CURRENT%SURFACE_EDGES_NUM
                IF(.NOT. USED_EDGE(I)) THEN
                    CURRENT_EDGE = I
                    EXIT
                END IF
            END DO
            
            INITIAL_EDGE = CURRENT_EDGE
            
            B = .TRUE.
            
            DO WHILE(B)
                J2 = SURFACE_CURRENT%SURFACE_EDGES(2,CURRENT_EDGE)
                I2 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,J2)
                CURRENT_EDGE = I2
                
                USED_EDGE(CURRENT_EDGE) = .TRUE.
		TEMP_LOCATION(CURRENT_EDGE) = PATCH_NUM
	
		IF(PRESENT(PATCH_BEFORE_INDEX)) THEN
		   DO J=1,SURFACE_CURRENT%SURFACE_EDGES_NUM
		      IF(TEMP_LOCATION(J) .EQ. PATCH_NUM) THEN	       	      
			   PATCH_BEFORE_INDEX(PATCH_NUM) =  SURFACE_CURRENT%EDGE_LOCATION(J)
			   EXIT
		      END IF
		   END DO
		END IF
                SURFACE_CURRENT%EDGE_LOCATION(CURRENT_EDGE) = TEMP_LOCATION(CURRENT_EDGE)
                
                TEMP = TEMP + 1
                
                IF(CURRENT_EDGE==INITIAL_EDGE) THEN
                    B = .FALSE.
                END IF
            END DO
            
            PATCH_NUM = PATCH_NUM + 1
        END DO

	DEALLOCATE(USED_EDGE)
	DEALLOCATE(TEMP_LOCATION)
	!ELSE

	!    DEALLOCATE(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP)
	!    NUM = 0
   	!    DO I=1, TEMP_PATCH_NUM
	!        IF(PATCH_INDEX(I) .NE. 0) THEN
	!	NUM = NUM +1
	!        END IF
	!    END DO

	!    ALLOCATE(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(NUM))
	!    IF(ALLOCATED(PATCH_PARENT)) THEN
	!	DEALLOCATE(PATCH_PARENT)
	!    END IF
	!    ALLOCATE(PATCH_PARENT(NUM))

   	!    DO I=1, NUM
	!        IF(PATCH_INDEX(I) .NE. 0 .AND. FLAG .EQ. .TRUE.) THEN
	!	SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(PATCH_INDEX(I)) = PATCH_ZIPPER_TYPE(I)
	!        END IF
	!    END DO

	!    DO I=1,NUM
	!	IF(PATCH_INDEX(I) .NE. 0) THEN
	!	PATCH_PARENT(PATCH_INDEX(I)) = PATCH_BEFORE_INDEX(I)
	!	END IF
	!    END DO

	!END IF
        
    END SUBROUTINE RESET_PATCH
    
    SUBROUTINE ATTACH_FLUID_CASE_IMPACT_ZONE()
        IMPLICIT NONE
        INTEGER :: I, IPZ, DIR, I1, I2
        REAL(8) :: R, TEMP
        LOGICAL :: B, FLAG
        
        FLAG = .FALSE.
        DIR = 1
        
        DO I=1,SURFACE_FLUID%SURFACE_EDGES_NUM
            IPZ = SURFACE_FLUID%EDGE_IMPACT_ZONE(2+1, I)
            IF(IPZ.NE.0) THEN
                CALL DISTANCE_EDGE_EDGE_TYPE(I,0,IPZ,2,DIR,  R,B)
                IF(B) THEN
                    IF(R < SURFACE_FLUID%MESH_SIZE / 30. .AND. SURFACE_FLUID%EDGE_ONINTERFACE(I) .NE. 2) THEN
                        FLAG = .TRUE.
                        EXIT
                    END IF
                END IF
            END IF
        END DO
        
        IF(FLAG) THEN
            DO I=1,SURFACE_FLUID%SURFACE_EDGES_NUM
                IPZ = SURFACE_FLUID%EDGE_IMPACT_ZONE(2+1, I)
                IF(IPZ.NE.0) THEN
                    CALL DISTANCE_EDGE_EDGE_TYPE(I,0,IPZ,2,DIR,  R,B)
                    IF(B) THEN
                        IF(R < SURFACE_FLUID%MESH_SIZE / 15. .AND. SURFACE_FLUID%EDGE_ONINTERFACE(I) .NE. 2) THEN
                            SURFACE_FLUID%EDGE_ONINTERFACE(I) = 2
			    
			    I1 = SURFACE_FLUID%SURFACE_EDGES(1,I)
			    I2 = SURFACE_FLUID%SURFACE_EDGES(2,I)
			    
			    CALL PROJECTION_SURFACE_POINT_TYPE(SURFACE_FLUID%SURFACE_POINTS(:,I1), 2, TEMP)
			    CALL PROJECTION_SURFACE_POINT_TYPE(SURFACE_FLUID%SURFACE_POINTS(:,I2), 2, TEMP)
			    
				!MODIFIED!
			    SURFACE_FLUID%EDGE_LOCATION(I) = 0
				!END MODIFIED!
                        END IF
                    END IF
                END IF
            END DO
        END IF
        
    END SUBROUTINE ATTACH_FLUID_CASE_IMPACT_ZONE

    SUBROUTINE ATTACH_PROPEL_FLUID_IMPACT_ZONE()
        IMPLICIT NONE
        INTEGER :: I, IPZ, DIR
        REAL(8) :: R
        LOGICAL :: B, FLAG
        
        FLAG = .FALSE.
        DIR = 1
        
        DO I=1,SURFACE_PROPEL%SURFACE_EDGES_NUM
            IPZ = SURFACE_PROPEL%EDGE_IMPACT_ZONE(0+1, I)
            IF(IPZ.NE.0) THEN
                CALL DISTANCE_EDGE_EDGE_TYPE(I,1,IPZ,0,DIR,  R,B)
                IF(B) THEN
                    IF(R < SURFACE_FLUID%MESH_SIZE / 100. .AND. SURFACE_PROPEL%EDGE_ONINTERFACE(I) .NE. 0) THEN
                        FLAG = .TRUE.
                        EXIT
                    END IF
                END IF
            END IF
        END DO
        
        IF(FLAG) THEN
            DO I=1,SURFACE_PROPEL%SURFACE_EDGES_NUM
                IPZ = SURFACE_PROPEL%EDGE_IMPACT_ZONE(0+1, I)
                IF(IPZ.NE.0) THEN
                    CALL DISTANCE_EDGE_EDGE_TYPE(I,1,IPZ,0,DIR,  R,B)
                    IF(B) THEN
                        IF(R < SURFACE_FLUID%MESH_SIZE / 50. .AND. SURFACE_PROPEL%EDGE_ONINTERFACE(I) .NE. 0) THEN
                            SURFACE_PROPEL%EDGE_ONINTERFACE(I) = 0
                        END IF
                    END IF
                END IF
            END DO
        END IF
        
    END SUBROUTINE ATTACH_PROPEL_FLUID_IMPACT_ZONE
    
    SUBROUTINE ZIPPER_PROPEL_IMPACT_ZONE(FLAG)
        IMPLICIT NONE
        INTEGER :: I,I1, I2, J, J1, J2, K, IPZ, IPZ1, IPZ2, DIR, PAIR_NUM, IND
        REAL(8) :: R, R1, R2, R3
	INTEGER, ALLOCATABLE :: MATCH_INDEX(:,:), PATCH_PARENT(:), PATCH_BEFORE_INDEX(:)

        LOGICAL :: B, FLAG, TEMPFLAG, THINFLAG
        
        FLAG = .FALSE.
        
	TEMPFLAG = .FALSE.
	THINFLAG = .FALSE.
	B = .TRUE.
        DIR = 0
	ALLOCATE(MATCH_INDEX(SURFACE_PROPEL%SURFACE_EDGES_NUM,2))
	ALLOCATE(PATCH_PARENT(SURFACE_PROPEL%SURFACE_EDGES_NUM))
        
	DO J=1,SURFACE_PROPEL%SURFACE_PATCHES_NUM
	   DO I=1,SURFACE_PROPEL%SURFACE_EDGES_NUM
	      IF(SURFACE_PROPEL%EDGE_LOCATION(I) .EQ. J) THEN
	      I1 = SURFACE_PROPEL%SURFACE_EDGES(1,I)
	      I2 = SURFACE_PROPEL%SURFACE_EDGES(2,I)
	      J1 = SURFACE_PROPEL%POINT_EDGE_CONNECTION(1,I1)
	      J2 = SURFACE_PROPEL%POINT_EDGE_CONNECTION(2,I2)
	      IPZ = SURFACE_PROPEL%EDGE_IMPACT_ZONE(1+1, I)
	      IPZ1 = SURFACE_PROPEL%EDGE_IMPACT_ZONE(1+1, J1)
	      IPZ2 = SURFACE_PROPEL%EDGE_IMPACT_ZONE(1+1, J2)
		   
		IF(IPZ.NE.0 .AND. IPZ1 .NE. 0 .AND. IPZ2 .NE. 0) THEN
		  CALL DISTANCE_EDGE_EDGE_TYPE(I,1,IPZ,1,DIR,  R1,B)
		  CALL DISTANCE_EDGE_EDGE_TYPE(J1,1,IPZ1,1,DIR,  R2,B)
		  CALL DISTANCE_EDGE_EDGE_TYPE(J2,1,IPZ2,1,DIR,  R3,B)
		      IF(MAX(ABS(R1),MAX(ABS(R2),ABS(R3))) .LT. SURFACE_FLUID%MESH_SIZE * 10.) THEN
			   IND = I
		           THINFLAG = .TRUE.
	   		   SURFACE_PROPEL%SURFACE_PATCHES_TOPCHANGE_TYP(SURFACE_PROPEL%EDGE_LOCATION(IND)) = 11
		           EXIT
		      END IF
	   	END IF
	      END IF
	   END DO
        END DO

        DO I=1,SURFACE_PROPEL%SURFACE_EDGES_NUM
            IPZ = SURFACE_PROPEL%EDGE_IMPACT_ZONE(1+1, I)
            IF(IPZ.NE.0) THEN
                CALL DISTANCE_EDGE_EDGE_TYPE(I,1,IPZ,1,DIR,  R,B)
                IF(R < SURFACE_FLUID%MESH_SIZE * 6.) THEN
                    TEMPFLAG = .TRUE.
                    EXIT
                END IF
            END IF
        END DO
        
	PAIR_NUM = 0
        IF(TEMPFLAG) THEN
            DO I=1,SURFACE_PROPEL%SURFACE_EDGES_NUM
                !write(*,*) I
                IPZ = SURFACE_PROPEL%EDGE_IMPACT_ZONE(1+1, I)
		!if(i .eq. 184) then
		!write(*,*) ipz, pair_num
		!end if
                IF(IPZ.NE.0) THEN
		    IF(SURFACE_PROPEL%EDGE_IMPACT_ZONE(1+1,IPZ) .EQ. I) THEN
   	                IF(PAIR_NUM .EQ. 0) THEN
		            PAIR_NUM = PAIR_NUM + 1
		            MATCH_INDEX(PAIR_NUM,1) = I
                            MATCH_INDEX(PAIR_NUM,2) = IPZ
                        ELSE
			    B = .TRUE.
                            DO J=1,PAIR_NUM
                                IF(MATCH_INDEX(J,2) .EQ. I) THEN
                                    B = .FALSE.
                                    EXIT
                                END IF
                            END DO

                            IF(B) THEN
                                PAIR_NUM = PAIR_NUM + 1
                                MATCH_INDEX(PAIR_NUM,1) = I
                                MATCH_INDEX(PAIR_NUM,2) = IPZ
                            END IF
                        END IF
                    END IF
                END IF

            END DO

            DO K=1,PAIR_NUM
                CALL DISTANCE_EDGE_EDGE_TYPE(MATCH_INDEX(K,1),1,MATCH_INDEX(K,2),1,DIR,  R,B)
                IF(MATCH_INDEX(K,2) .NE. 0) THEN
                   IF(R < SURFACE_FLUID%MESH_SIZE * 8.) THEN
                        !CALL REMOVE_LARGE_REGION(1, SURFACE_PROPEL%EDGE_LOCATION(MATCH_INDEX(K,1)))
                        CALL ATTACH_TWO_EDGES(1, MATCH_INDEX(K,1), MATCH_INDEX(K,2))
	   		SURFACE_PROPEL%SURFACE_PATCHES_TOPCHANGE_TYP(SURFACE_PROPEL%EDGE_LOCATION(MATCH_INDEX(K,1))) = 2
			FLAG = .TRUE.
			!EXIT
                    END IF
                END IF
            END DO

            CALL RESET_PATCH(1, PATCH_BEFORE_INDEX = PATCH_BEFORE_INDEX)                
            CALL REMOVE_SMALL_REGIONS(1, PATCH_BEFORE_INDEX, PATCH_PARENT = PATCH_PARENT, FLAG = FLAG)
        END IF
        
        DEALLOCATE(MATCH_INDEX)
        
    END SUBROUTINE ZIPPER_PROPEL_IMPACT_ZONE
    
    SUBROUTINE ZIPPER_FLUID_IMPACT_ZONE(FLAG)
        IMPLICIT NONE
        INTEGER :: I, J, K, IPZ, DIR, PAIR_NUM
        REAL(8) :: R
	INTEGER, ALLOCATABLE :: MATCH_INDEX(:,:)
	INTEGER, ALLOCATABLE :: PATCH_PARENT(:), PATCH_BEFORE_INDEX(:)
        LOGICAL :: B, FLAG
        
        FLAG = .FALSE.
        DIR = 0
        B = .TRUE.
  
	ALLOCATE(MATCH_INDEX(SURFACE_FLUID%SURFACE_EDGES_NUM,2))

        DO I=1,SURFACE_FLUID%SURFACE_EDGES_NUM
            IPZ = SURFACE_FLUID%EDGE_IMPACT_ZONE(0+1, I)
            IF(IPZ.NE.0) THEN
                CALL DISTANCE_EDGE_EDGE_TYPE(I,0,IPZ,0,DIR,  R,B)
                IF(R < -SURFACE_FLUID%MESH_SIZE / 50.) THEN
                    FLAG = .TRUE.
                    EXIT
                END IF
            END IF
        END DO

	PAIR_NUM = 0
        IF(FLAG) THEN
            DO I=1,SURFACE_FLUID%SURFACE_EDGES_NUM

                IPZ = SURFACE_FLUID%EDGE_IMPACT_ZONE(0+1, I)
                IF(IPZ.NE.0) THEN
		    IF(SURFACE_FLUID%EDGE_IMPACT_ZONE(0+1,IPZ) .EQ. I) THEN
   	                IF(PAIR_NUM .EQ. 0) THEN
		            PAIR_NUM = PAIR_NUM + 1
		            MATCH_INDEX(PAIR_NUM,1) = I
                            MATCH_INDEX(PAIR_NUM,2) = IPZ
                        ELSE
                            DO J=1,PAIR_NUM
                                IF(MATCH_INDEX(J,2) .EQ. I) THEN
                                    B = .FALSE.
                                    EXIT
                                END IF
                            END DO

                            IF(B) THEN
                                PAIR_NUM = PAIR_NUM + 1
                                MATCH_INDEX(PAIR_NUM,1) = I
                                MATCH_INDEX(PAIR_NUM,2) = IPZ
                            END IF
                        END IF
                    END IF
                END IF

            END DO
                
            DO K=1,PAIR_NUM
                CALL DISTANCE_EDGE_EDGE_TYPE(MATCH_INDEX(K,1),0,MATCH_INDEX(K,2),0,DIR,  R,B)
                IF(MATCH_INDEX(K,2) .NE. 0) THEN
                    IF(R < -SURFACE_FLUID%MESH_SIZE / 100.) THEN
                        CALL ATTACH_TWO_EDGES(0, MATCH_INDEX(K,1), MATCH_INDEX(K,2))
                    END IF
                END IF
            END DO

	    ALLOCATE(PATCH_PARENT(1))
	    PATCH_PARENT(:) = 1
            CALL RESET_PATCH(0, PATCH_BEFORE_INDEX)
            CALL REMOVE_SMALL_REGIONS(0, PATCH_BEFORE_INDEX)
        END IF
        
    END SUBROUTINE ZIPPER_FLUID_IMPACT_ZONE

    SUBROUTINE EDGE_SPLITTING_COLLAPSING(TYP, FLAG, FLAG_ARRAY)
	IMPLICIT NONE
        INTEGER :: TYP
        LOGICAL :: FLAG
        INTEGER, OPTIONAL :: FLAG_ARRAY(:)
        
        REAL(8) , ALLOCATABLE :: TEMPPOINT(:,:)
        INTEGER, ALLOCATABLE :: TEMPEDGE(:,:)
        INTEGER, ALLOCATABLE :: TEMPPOINT_TYPE(:)
        
        INTEGER, ALLOCATABLE :: TEMP_NEWONINTERFACE(:)
        INTEGER, ALLOCATABLE :: TEMP_NEWLOCATION(:)
        REAL(8), ALLOCATABLE :: TEMP_NEWEDGELENGTH(:)
        INTEGER, ALLOCATABLE :: TEMP_CONNECTION(:,:)
 	INTEGER, ALLOCATABLE :: TEMP_ABLATION_FLAG(:)
    
        INTEGER :: TEMP_POINT_NUM, TEMP_EDGE_NUM
        REAL(8) :: XY1(2),XY2(2),XYN(2),XYC(2)
        REAL(8) :: L,R
    
        INTEGER :: I, J1, J2, I1, I2, ITER
        
        INTEGER :: CURRENT_EDGE, INITIAL_EDGE
        REAL(8) :: CLUSTER_LENGTH
        REAL(8) :: CLUSTER_INITIAL_LENGTH
        INTEGER :: IMIN, IMAX
        REAL(8) :: RMIN, RMAX
        
        LOGICAL, ALLOCATABLE :: SPLITTING_EDGE(:)
        LOGICAL, ALLOCATABLE :: COLLAPSING_EDGE(:)

        LOGICAL :: B1, B2
        INTEGER :: PATCH_NUM
        INTEGER :: ONE_PATCH_EDGES_NUM
        INTEGER, ALLOCATABLE :: INITIAL_CURRENT_EDGES(:)
        INTEGER :: SPLITTING_COLLAPSING_NUMBER, ALL_SPLITTING_COLLAPSING_NUMBER
        REAL(8), ALLOCATABLE :: SPLITTING_COLLAPSING_R(:)

        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF
        
        FLAG = .FALSE.
        
        ALLOCATE(SPLITTING_EDGE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(COLLAPSING_EDGE(2*SURFACE_CURRENT%SURFACE_EDGES_NUM))
        SPLITTING_EDGE(:) = .FALSE.
        COLLAPSING_EDGE(:) = .FALSE.
        
        ALLOCATE(SPLITTING_COLLAPSING_R(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALL_SPLITTING_COLLAPSING_NUMBER = 0
        
        IF(TYP==1) THEN
            ALLOCATE(INITIAL_CURRENT_EDGES(100))
            PATCH_NUM = 0
            B1 = .TRUE.
            DO WHILE(B1)
               B1 = .FALSE.
               DO I = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
                   IF(SURFACE_CURRENT%EDGE_LOCATION(I)==PATCH_NUM + 1) THEN
                       PATCH_NUM = PATCH_NUM + 1
                       INITIAL_CURRENT_EDGES(PATCH_NUM) = I
                       B1 = .TRUE.
                       EXIT
                   END IF
               END DO
            END DO
        ELSE
            PATCH_NUM = 1
            ALLOCATE(INITIAL_CURRENT_EDGES(1))
            INITIAL_CURRENT_EDGES(1) = 1
        END IF
        DO ITER = 1, PATCH_NUM
            SPLITTING_COLLAPSING_NUMBER = 0
            SPLITTING_COLLAPSING_R = 1.
            ONE_PATCH_EDGES_NUM = 0
            
            CURRENT_EDGE = INITIAL_CURRENT_EDGES(ITER)
            
            B1 = .TRUE.
            DO WHILE(B1)
                J1 = SURFACE_CURRENT%SURFACE_EDGES(1,CURRENT_EDGE)
                I1 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,J1)
                
                IF(SURFACE_CURRENT%POINT_TYPE(J1)==2 .OR. SURFACE_CURRENT%POINT_TYPE(J1)==3) THEN
                    B1 = .FALSE.
                END IF
                
                IF(B1) THEN
                    CURRENT_EDGE = I1
                END IF
            END DO
            
            INITIAL_EDGE = CURRENT_EDGE
            
            B2 = .TRUE.
            DO WHILE(B2)
                
                CLUSTER_LENGTH = 0.
                CLUSTER_INITIAL_LENGTH = 0.
                IMAX = 0
                IMIN = 0
                RMAX = 0.
                RMIN = 10.
                
                B1 = .TRUE.
                DO WHILE(B1)
                    ONE_PATCH_EDGES_NUM = ONE_PATCH_EDGES_NUM + 1
                    
                    J1 = SURFACE_CURRENT%SURFACE_EDGES(1,CURRENT_EDGE)
                    J2 = SURFACE_CURRENT%SURFACE_EDGES(2,CURRENT_EDGE)
                    I2 = SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,J2)
                    
                    L = SQRT(DOT_PRODUCT(SURFACE_CURRENT%SURFACE_POINTS(:,J1) - SURFACE_CURRENT%SURFACE_POINTS(:,J2), SURFACE_CURRENT%SURFACE_POINTS(:,J1) - SURFACE_CURRENT%SURFACE_POINTS(:,J2)))
                    R = L/SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(CURRENT_EDGE)
                    
                    IF(R>1.) THEN
                        SPLITTING_COLLAPSING_R(CURRENT_EDGE) = R
                    ELSE
                        SPLITTING_COLLAPSING_R(CURRENT_EDGE) = 1./R
                    END IF

		    !IF(L<1/3.*SURFACE_FLUID%MESH_SIZE) THEN
                    !    COLLAPSING_EDGE(CURRENT_EDGE) = .TRUE.
                    !    FLAG = .TRUE.
                    !    SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER + 1
                    !    SPLITTING_COLLAPSING_R(CURRENT_EDGE) = 1./R
                    !ELSE
                    IF(R<0.5) THEN
                        COLLAPSING_EDGE(CURRENT_EDGE) = .TRUE.
                        FLAG = .TRUE.
                        SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER + 1
		    END IF

                    IF(R>2.) THEN
                        SPLITTING_EDGE(CURRENT_EDGE) = .TRUE.
                        FLAG = .TRUE.
                        SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER + 1
                    END IF
 
                    IF(R<RMIN) THEN
                        RMIN = R
                        IMIN = CURRENT_EDGE
                    END IF

            	    IF(R>RMAX) THEN
                        RMAX = R
                        IMAX = CURRENT_EDGE
            	    END IF

                    CLUSTER_LENGTH = CLUSTER_LENGTH + L
                    CLUSTER_INITIAL_LENGTH = CLUSTER_INITIAL_LENGTH + SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(CURRENT_EDGE)
                    
                    IF(SURFACE_CURRENT%POINT_TYPE(J2)==2 .OR. SURFACE_CURRENT%POINT_TYPE(J2)==3) THEN
                        B1 = .FALSE.
                    END IF
                    
                    !! END MODIFIED
                    
                    CURRENT_EDGE = I2
                END DO
                
		IF(CLUSTER_LENGTH > CLUSTER_INITIAL_LENGTH + SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(IMAX)) THEN
                    SPLITTING_EDGE(IMAX) = .TRUE.
                    FLAG = .TRUE.
                    SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER + 1
		END IF
		
		IF(CLUSTER_LENGTH < CLUSTER_INITIAL_LENGTH - SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(IMIN)) THEN
                    COLLAPSING_EDGE(IMIN) = .TRUE.
                    FLAG = .TRUE.
                    SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER + 1
                END IF              
                
                IF(CURRENT_EDGE==INITIAL_EDGE) THEN
                    B2 = .FALSE.
                END IF
            END DO
        
            IF(TYP==1 .AND. MOD(ONE_PATCH_EDGES_NUM + SPLITTING_COLLAPSING_NUMBER,2)==1) THEN
                IMAX = 0
                IMIN = 0
                RMAX = 0.
                RMIN = 10.
                DO I=1,SURFACE_CURRENT%SURFACE_EDGES_NUM
                    IF(SURFACE_CURRENT%EDGE_LOCATION(I)==ITER .AND. ((SPLITTING_EDGE(I) .OR. COLLAPSING_EDGE(I)) .AND. SPLITTING_COLLAPSING_R(I)<RMIN)) THEN
                        RMIN = SPLITTING_COLLAPSING_R(I)
                        IMIN = I
                    END IF
                    
                    IF(SURFACE_CURRENT%EDGE_LOCATION(I)==ITER .AND. (.NOT. SPLITTING_EDGE(I) .AND. .NOT. COLLAPSING_EDGE(I) .AND. SPLITTING_COLLAPSING_R(I)>RMAX)) THEN
                        RMAX = SPLITTING_COLLAPSING_R(I)
                        IMAX = I
                    END IF
                END DO
                    
                IF(RMIN < 2.) THEN
                    SPLITTING_EDGE(IMIN) = .FALSE.
                    COLLAPSING_EDGE(IMIN) = .FALSE.
                    
                    SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER - 1
                ELSE
                    J1 = SURFACE_CURRENT%SURFACE_EDGES(1,IMAX)
                    J2 = SURFACE_CURRENT%SURFACE_EDGES(2,IMAX)
                    
                    L = SQRT(DOT_PRODUCT(SURFACE_CURRENT%SURFACE_POINTS(:,J1) - SURFACE_CURRENT%SURFACE_POINTS(:,J2), SURFACE_CURRENT%SURFACE_POINTS(:,J1) - SURFACE_CURRENT%SURFACE_POINTS(:,J2)))
                    R = L/SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(IMAX)
                    
                    IF(R > 1.) THEN
                        SPLITTING_EDGE(IMAX) = .TRUE.
                    ELSE
                        COLLAPSING_EDGE(IMAX) = .TRUE.
                    END IF
                    
                    SPLITTING_COLLAPSING_NUMBER = SPLITTING_COLLAPSING_NUMBER + 1
                END IF
            END IF
            
            ALL_SPLITTING_COLLAPSING_NUMBER = ALL_SPLITTING_COLLAPSING_NUMBER + SPLITTING_COLLAPSING_NUMBER
        END DO
        
        IF(ALL_SPLITTING_COLLAPSING_NUMBER==0) THEN
            FLAG = .FALSE.
        END IF
       
        IF(FLAG) THEN
                
                !! SPLITTING !!
                
                ALLOCATE(TEMPPOINT(2,2*SURFACE_CURRENT%SURFACE_POINTS_NUM))
                ALLOCATE(TEMPEDGE(2,2*SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMPPOINT_TYPE(2*SURFACE_CURRENT%SURFACE_POINTS_NUM))
            
                ALLOCATE(TEMP_NEWONINTERFACE(2*SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMP_NEWLOCATION(2*SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMP_NEWEDGELENGTH(2*SURFACE_CURRENT%SURFACE_EDGES_NUM))
            	ALLOCATE(TEMP_ABLATION_FLAG(2*SURFACE_CURRENT%SURFACE_EDGES_NUM))
                TEMP_POINT_NUM = SURFACE_CURRENT%SURFACE_POINTS_NUM
                TEMP_EDGE_NUM = SURFACE_CURRENT%SURFACE_EDGES_NUM
                
                !$OMP PARALLEL DO PRIVATE(I)
                DO I=1,SURFACE_CURRENT%SURFACE_POINTS_NUM
                    TEMPPOINT(:,I) = SURFACE_CURRENT%SURFACE_POINTS(:,I)
                    TEMPPOINT_TYPE(I) = SURFACE_CURRENT%POINT_TYPE(I)
                END DO
                !$OMP END PARALLEL DO
                
                !$OMP PARALLEL DO PRIVATE(I)
                DO I=1,SURFACE_CURRENT%SURFACE_EDGES_NUM
                    TEMPEDGE(:,I) = SURFACE_CURRENT%SURFACE_EDGES(:,I)
                    TEMP_NEWONINTERFACE(I) = SURFACE_CURRENT%EDGE_ONINTERFACE(I)
                
                    IF(TYP==0 .OR. TYP==1) THEN
                        TEMP_NEWLOCATION(I) = SURFACE_CURRENT%EDGE_LOCATION(I)
                    END IF
                
                    TEMP_NEWEDGELENGTH(I) = SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(I)
		    TEMP_ABLATION_FLAG(I) = SURFACE_CURRENT%EDGE_ABLATION_FLAG(I)
                END DO
                !$OMP END PARALLEL DO 
            
                DO I=1,SURFACE_CURRENT%SURFACE_EDGES_NUM
            
                    XY1 = TEMPPOINT(:,TEMPEDGE(1,I))
                    XY2 = TEMPPOINT(:,TEMPEDGE(2,I))
                    
                    IF(SPLITTING_EDGE(I)) THEN
write(*,*) 'splitting_edge:', i                    
                        IF(TYP==1) THEN
                            FLAG_ARRAY(TEMP_NEWLOCATION(I)) = 1
			    IF(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(TEMP_NEWLOCATION(I)) == 0) THEN
			        SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(TEMP_NEWLOCATION(I)) = 1
			    END IF
                            !CYCLE
                        END IF
                        
                        XYN = (XY1+XY2)/2.
                        
                        TEMP_POINT_NUM = TEMP_POINT_NUM+1
                        TEMP_EDGE_NUM = TEMP_EDGE_NUM+1
                    
                        TEMPPOINT(:,TEMP_POINT_NUM) = XYN
                
                        TEMPEDGE(1,TEMP_EDGE_NUM) = TEMP_POINT_NUM
                        TEMPEDGE(2,TEMP_EDGE_NUM) = TEMPEDGE(2,I)
                    
                        TEMPEDGE(2,I) = TEMP_POINT_NUM
                    
                        TEMPPOINT_TYPE(TEMP_POINT_NUM) = 1
                        TEMP_NEWONINTERFACE(TEMP_EDGE_NUM) = TEMP_NEWONINTERFACE(I)
                    
                        IF(TYP==0 .OR. TYP==1) THEN
                            TEMP_NEWLOCATION(TEMP_EDGE_NUM) = TEMP_NEWLOCATION(I)
                        END IF
                    
                        TEMP_NEWEDGELENGTH(TEMP_EDGE_NUM) = TEMP_NEWEDGELENGTH(I)
			TEMP_ABLATION_FLAG(TEMP_EDGE_NUM) = TEMP_ABLATION_FLAG(I)
                        
                    END IF
          
                END DO
           
                IF(TYP==0 .OR. TYP==1) THEN
                    CALL RESET_SURFACE(TYP, .TRUE., TEMP_POINT_NUM, TEMP_EDGE_NUM, SURFACE_POINTS = TEMPPOINT, SURFACE_EDGES = TEMPEDGE, &
                    SURFACE_INITIAL_EDGE_LENGTH = TEMP_NEWEDGELENGTH, POINT_TYPE = TEMPPOINT_TYPE, EDGE_ONINTERFACE = TEMP_NEWONINTERFACE, &
                    EDGE_LOCATION = TEMP_NEWLOCATION, EDGE_ABLATION_FLAG = TEMP_ABLATION_FLAG)
                ELSE
                    CALL RESET_SURFACE(TYP, .TRUE., TEMP_POINT_NUM, TEMP_EDGE_NUM, SURFACE_POINTS = TEMPPOINT, SURFACE_EDGES = TEMPEDGE, &
                    SURFACE_INITIAL_EDGE_LENGTH = TEMP_NEWEDGELENGTH, POINT_TYPE = TEMPPOINT_TYPE, EDGE_ONINTERFACE = TEMP_NEWONINTERFACE)
                END IF
            
            
                DEALLOCATE(TEMPPOINT_TYPE)
                
                DEALLOCATE(TEMPPOINT)
                DEALLOCATE(TEMPEDGE)
                
                DEALLOCATE(TEMP_NEWONINTERFACE)
            
                DEALLOCATE(TEMP_NEWLOCATION)
                DEALLOCATE(TEMP_NEWEDGELENGTH)
                DEALLOCATE(TEMP_ABLATION_FLAG)
            
                !! COLLAPSING !!
            
                ALLOCATE(TEMPPOINT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
                ALLOCATE(TEMPEDGE(2,SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMPPOINT_TYPE(SURFACE_CURRENT%SURFACE_POINTS_NUM))
            
                ALLOCATE(TEMP_NEWONINTERFACE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMP_NEWLOCATION(SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMP_NEWEDGELENGTH(SURFACE_CURRENT%SURFACE_EDGES_NUM))
                ALLOCATE(TEMP_CONNECTION(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
            	ALLOCATE(TEMP_ABLATION_FLAG(2*SURFACE_CURRENT%SURFACE_EDGES_NUM))

                TEMP_POINT_NUM = SURFACE_CURRENT%SURFACE_POINTS_NUM
                TEMP_EDGE_NUM = SURFACE_CURRENT%SURFACE_EDGES_NUM
                
                !$OMP PARALLEL DO PRIVATE(I)
                DO I=1,SURFACE_CURRENT%SURFACE_POINTS_NUM
                    TEMPPOINT(:,I) = SURFACE_CURRENT%SURFACE_POINTS(:,I)
                    TEMPPOINT_TYPE(I) = SURFACE_CURRENT%POINT_TYPE(I)
                    TEMP_CONNECTION(:,I) = SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,I)
                END DO
                !$OMP END PARALLEL DO
                
                !$OMP PARALLEL DO PRIVATE(I)
                DO I=1,SURFACE_CURRENT%SURFACE_EDGES_NUM
                    TEMPEDGE(:,I) = SURFACE_CURRENT%SURFACE_EDGES(:,I)
                    TEMP_NEWONINTERFACE(I) = SURFACE_CURRENT%EDGE_ONINTERFACE(I)
                
                    IF(TYP==0 .OR. TYP==1) THEN
                        TEMP_NEWLOCATION(I) = SURFACE_CURRENT%EDGE_LOCATION(I)
                    END IF
                
                    TEMP_NEWEDGELENGTH(I) = SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(I)
		    TEMP_ABLATION_FLAG(I) = SURFACE_CURRENT%EDGE_ABLATION_FLAG(I)
                END DO
                !$OMP END PARALLEL DO
                
                I = 1
                DO WHILE(I <= TEMP_EDGE_NUM)                 
                
                    IF(COLLAPSING_EDGE(I)) THEN
write(*,*) 'collapsing_edge:', i
	  		J1 = TEMPEDGE(1,I)
			J2 = TEMPEDGE(2,I)
		        
                        XY1 = TEMPPOINT(:,J1)
                        XY2 = TEMPPOINT(:,J2)

                        IF(TYP==1) THEN
                            FLAG_ARRAY(TEMP_NEWLOCATION(I)) = 1
			    IF(SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(TEMP_NEWLOCATION(I)) == 0) THEN
			        SURFACE_CURRENT%SURFACE_PATCHES_TOPCHANGE_TYP(TEMP_NEWLOCATION(I)) = 1
			    END IF
                        END IF
                        
                        XYC = (XY1+XY2)/2.
                        IF(TEMPPOINT_TYPE(J1) > TEMPPOINT_TYPE(J2)) THEN
                            XYN = XY1
                        ELSE IF(TEMPPOINT_TYPE(J2) > TEMPPOINT_TYPE(J1)) THEN
                            XYN = XY2
                        ELSE
                            XYN = XYC
                        END IF
                        
                        !! END MODIFIED
                        
                        TEMPPOINT(:,J1) = XYN
                        TEMPPOINT_TYPE(J1) = MAX(TEMPPOINT_TYPE(J1), TEMPPOINT_TYPE(J2))
                        
                        TEMP_CONNECTION(2,J1) = TEMP_CONNECTION(2,J2)
                        TEMPEDGE(1,TEMP_CONNECTION(2,J1)) = J1
                        
                        
                        IF(J2 .NE. TEMP_POINT_NUM) THEN
                            TEMPPOINT(:,J2) = TEMPPOINT(:,TEMP_POINT_NUM)
                            TEMPPOINT_TYPE(J2) = TEMPPOINT_TYPE(TEMP_POINT_NUM)
                            TEMP_CONNECTION(:,J2) = TEMP_CONNECTION(:,TEMP_POINT_NUM)
                        
                            TEMPEDGE(2,TEMP_CONNECTION(1,J2)) = J2
                            TEMPEDGE(1,TEMP_CONNECTION(2,J2)) = J2
                        END IF
                        
                        IF(I .NE. TEMP_EDGE_NUM) THEN
                            TEMPEDGE(:,I) = TEMPEDGE(:,TEMP_EDGE_NUM)
                            TEMP_NEWONINTERFACE(I) = TEMP_NEWONINTERFACE(TEMP_EDGE_NUM)
                            IF(TYP==0 .OR. TYP==1) THEN
                                TEMP_NEWLOCATION(I) = TEMP_NEWLOCATION(TEMP_EDGE_NUM)
                            END IF
                            TEMP_NEWEDGELENGTH(I) = TEMP_NEWEDGELENGTH(TEMP_EDGE_NUM)
                            
                            COLLAPSING_EDGE(I) = COLLAPSING_EDGE(TEMP_EDGE_NUM)
                        
                            TEMP_CONNECTION(2,TEMPEDGE(1,I)) = I
                            TEMP_CONNECTION(1,TEMPEDGE(2,I)) = I
  			    TEMP_ABLATION_FLAG(I) = TEMP_ABLATION_FLAG(TEMP_EDGE_NUM)
                        END IF
                        
                                        
                        TEMP_POINT_NUM = TEMP_POINT_NUM-1
                        TEMP_EDGE_NUM = TEMP_EDGE_NUM-1
                    ELSE
                        I = I + 1
                    END IF
          
                END DO
            
                IF(TYP==0 .OR. TYP==1) THEN
                    CALL RESET_SURFACE(TYP, .TRUE., TEMP_POINT_NUM, TEMP_EDGE_NUM, SURFACE_POINTS = TEMPPOINT, SURFACE_EDGES = TEMPEDGE, &
                    SURFACE_INITIAL_EDGE_LENGTH = TEMP_NEWEDGELENGTH, POINT_EDGE_CONNECTION = TEMP_CONNECTION, POINT_TYPE = TEMPPOINT_TYPE, EDGE_ONINTERFACE = TEMP_NEWONINTERFACE, &
                    EDGE_LOCATION = TEMP_NEWLOCATION, EDGE_ABLATION_FLAG = TEMP_ABLATION_FLAG)
                ELSE
                    CALL RESET_SURFACE(TYP, .TRUE., TEMP_POINT_NUM, TEMP_EDGE_NUM, SURFACE_POINTS = TEMPPOINT, SURFACE_EDGES = TEMPEDGE, &
                    SURFACE_INITIAL_EDGE_LENGTH = TEMP_NEWEDGELENGTH, POINT_EDGE_CONNECTION = TEMP_CONNECTION, POINT_TYPE = TEMPPOINT_TYPE, EDGE_ONINTERFACE = TEMP_NEWONINTERFACE)
                END IF
            
            
                DEALLOCATE(TEMPPOINT_TYPE)
                
                DEALLOCATE(TEMPPOINT)
                DEALLOCATE(TEMPEDGE)
                
                DEALLOCATE(TEMP_NEWONINTERFACE)
            
                DEALLOCATE(TEMP_NEWLOCATION)
                DEALLOCATE(TEMP_NEWEDGELENGTH)
                DEALLOCATE(TEMP_CONNECTION)
		DEALLOCATE(TEMP_ABLATION_FLAG)
                
                DO I = 1,5
                    CALL MODIFIED_NULLSPACE_SMOOTHING(TYP)
                END DO
                
            END IF
        
!	IF(TYP .EQ. 1) THEN
!	    CALL CLASSIFY_PATCH(1)
!	END IF

        DEALLOCATE(INITIAL_CURRENT_EDGES)
        DEALLOCATE(SPLITTING_EDGE)
        DEALLOCATE(COLLAPSING_EDGE)
        DEALLOCATE(SPLITTING_COLLAPSING_R)
    
    END SUBROUTINE EDGE_SPLITTING_COLLAPSING  

    SUBROUTINE REARRANGE_EDGE(TYP,POINT_NUM,POINT,EDGE_NUM,EDGE)
        IMPLICIT NONE

	INTEGER :: TYP, POINT_NUM ,EDGE_NUM
	REAL(8), ALLOCATABLE :: POINT(:,:)
	INTEGER, ALLOCATABLE :: EDGE(:,:)
        
        REAL(8), ALLOCATABLE :: SURFACE_INITIAL_EDGE_LENGTH(:)
        REAL(8), ALLOCATABLE :: EDGE_B_RATE(:)
        REAL(8), ALLOCATABLE :: POINT_VELOCITY(:,:)
        REAL(8), ALLOCATABLE :: POINT_DISPLACEMENT(:,:)
        INTEGER, ALLOCATABLE :: POINT_EDGE_CONNECTION(:,:)
        INTEGER, ALLOCATABLE :: POINT_TYPE(:)
        INTEGER, ALLOCATABLE :: EDGE_LOCATION(:)
        INTEGER, ALLOCATABLE :: EDGE_ONINTERFACE(:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDPT(:,:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDEDGE(:,:)
        REAL(8), ALLOCATABLE :: EDGE_PRESSURE(:)
        REAL(8), ALLOCATABLE :: POINT_FORCE(:,:)
        INTEGER, ALLOCATABLE :: EDGE_IMPACT_ZONE(:,:)
	INTEGER, ALLOCATABLE :: EDGE_ABLATION_FLAG(:)        

        INTEGER :: I, J, J1, J2
        
        INTEGER, ALLOCATABLE :: POINT_INDEX(:)
        INTEGER, ALLOCATABLE :: EDGE_INDEX(:)

	REAL(8) :: L
        
        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF               
        
        ALLOCATE(POINT_INDEX(SURFACE_CURRENT%SURFACE_POINTS_NUM))      
        ALLOCATE(EDGE_INDEX(SURFACE_CURRENT%SURFACE_EDGES_NUM))    
     
	DO I = 1, POINT_NUM
	    DO J = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
		L = SQRT(DOT_PRODUCT(POINT(:,I)-SURFACE_CURRENT%SURFACE_POINTS(:,J),POINT(:,I)-SURFACE_CURRENT%SURFACE_POINTS(:,J)))
		IF(L<1e-7) THEN
		    POINT_INDEX(J)= I
		    EXIT
		END IF
	    END DO
	END DO

        SURFACE_CURRENT%SURFACE_POINTS = POINT

	DO I = 1, EDGE_NUM
	    J1 = EDGE(1,I)
	    J2 = EDGE(2,I)
	    DO J = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
		IF(POINT_INDEX(J) == J1) THEN
		    EDGE_INDEX(SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,J)) = I
		END IF
	    END DO
	END DO      
        
	SURFACE_CURRENT%SURFACE_EDGES = EDGE

        ALLOCATE(SURFACE_INITIAL_EDGE_LENGTH(EDGE_NUM))
        ALLOCATE(EDGE_B_RATE(EDGE_NUM))
        ALLOCATE(POINT_VELOCITY(2,POINT_NUM))
        ALLOCATE(POINT_DISPLACEMENT(2,POINT_NUM))
        ALLOCATE(POINT_EDGE_CONNECTION(2,POINT_NUM))
        ALLOCATE(POINT_TYPE(POINT_NUM))
        ALLOCATE(EDGE_LOCATION(EDGE_NUM))
        ALLOCATE(EDGE_ONINTERFACE(EDGE_NUM))
        ALLOCATE(POINT_RELATEDPT(3,POINT_NUM))
        ALLOCATE(POINT_RELATEDEDGE(3,POINT_NUM))
        ALLOCATE(EDGE_PRESSURE(EDGE_NUM))
        ALLOCATE(POINT_FORCE(2,POINT_NUM))
        ALLOCATE(EDGE_IMPACT_ZONE(3,EDGE_NUM))
        ALLOCATE(EDGE_ABLATION_FLAG(EDGE_NUM))

        DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            IF(POINT_INDEX(I).NE.0) THEN
                POINT_VELOCITY(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_VELOCITY(:,I)
                POINT_DISPLACEMENT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_DISPLACEMENT(:,I)
                POINT_EDGE_CONNECTION(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,I)
                POINT_TYPE(POINT_INDEX(I)) = SURFACE_CURRENT%POINT_TYPE(I)
                POINT_RELATEDPT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDPT(:,I)
                POINT_RELATEDEDGE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDEDGE(:,I)
                POINT_FORCE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_FORCE(:,I)
            END IF
        END DO

        DO J = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            POINT_EDGE_CONNECTION(:,J) = EDGE_INDEX(POINT_EDGE_CONNECTION(:,J))
        END DO    
        
        DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
            IF(EDGE_INDEX(J).NE.0) THEN
                SURFACE_INITIAL_EDGE_LENGTH(EDGE_INDEX(J)) = SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J)
                EDGE_B_RATE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_B_RATE(J)
                EDGE_LOCATION(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_LOCATION(J)
                EDGE_ONINTERFACE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ONINTERFACE(J)
                EDGE_PRESSURE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_PRESSURE(J)
                EDGE_IMPACT_ZONE(:,EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_IMPACT_ZONE(:,J)
		EDGE_ABLATION_FLAG(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ABLATION_FLAG(J)
            END IF
        END DO
        
        SURFACE_CURRENT%POINT_VELOCITY = POINT_VELOCITY
        SURFACE_CURRENT%POINT_DISPLACEMENT = POINT_DISPLACEMENT
        SURFACE_CURRENT%POINT_EDGE_CONNECTION = POINT_EDGE_CONNECTION
        SURFACE_CURRENT%POINT_TYPE = POINT_TYPE
        SURFACE_CURRENT%POINT_RELATEDPT = POINT_RELATEDPT
        SURFACE_CURRENT%POINT_RELATEDEDGE = POINT_RELATEDEDGE
        SURFACE_CURRENT%POINT_FORCE = POINT_FORCE

        SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH = SURFACE_INITIAL_EDGE_LENGTH
        SURFACE_CURRENT%EDGE_B_RATE = EDGE_B_RATE
        SURFACE_CURRENT%EDGE_LOCATION = EDGE_LOCATION
        SURFACE_CURRENT%EDGE_ONINTERFACE = EDGE_ONINTERFACE
        SURFACE_CURRENT%EDGE_PRESSURE = EDGE_PRESSURE
        SURFACE_CURRENT%EDGE_IMPACT_ZONE = EDGE_IMPACT_ZONE
        SURFACE_CURRENT%EDGE_ABLATION_FLAG = EDGE_ABLATION_FLAG      
        
        DEALLOCATE(SURFACE_INITIAL_EDGE_LENGTH)
        DEALLOCATE(EDGE_B_RATE)
        DEALLOCATE(POINT_VELOCITY)
        DEALLOCATE(POINT_DISPLACEMENT)
        DEALLOCATE(POINT_EDGE_CONNECTION)
        DEALLOCATE(POINT_TYPE)
        DEALLOCATE(EDGE_LOCATION)
        DEALLOCATE(EDGE_ONINTERFACE)
        DEALLOCATE(POINT_RELATEDPT)
        DEALLOCATE(POINT_RELATEDEDGE)
        DEALLOCATE(EDGE_PRESSURE)
        DEALLOCATE(POINT_FORCE)
        DEALLOCATE(EDGE_IMPACT_ZONE)
        DEALLOCATE(EDGE_ABLATION_FLAG)

    END SUBROUTINE

    SUBROUTINE REARRANGE_INDEX(TYP)
        IMPLICIT NONE
        REAL(8), ALLOCATABLE :: NEWPOINT(:,:) 
        INTEGER, ALLOCATABLE :: NEWEDGE(:,:)
        
        REAL(8), ALLOCATABLE :: SURFACE_INITIAL_EDGE_LENGTH(:)
        REAL(8), ALLOCATABLE :: EDGE_B_RATE(:)
        REAL(8), ALLOCATABLE :: POINT_VELOCITY(:,:)
        REAL(8), ALLOCATABLE :: POINT_DISPLACEMENT(:,:)
        INTEGER, ALLOCATABLE :: POINT_EDGE_CONNECTION(:,:)
        INTEGER, ALLOCATABLE :: POINT_TYPE(:)
        INTEGER, ALLOCATABLE :: EDGE_LOCATION(:)
        INTEGER, ALLOCATABLE :: EDGE_ONINTERFACE(:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDPT(:,:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDEDGE(:,:)
        REAL(8), ALLOCATABLE :: EDGE_PRESSURE(:)
        REAL(8), ALLOCATABLE :: POINT_FORCE(:,:)
        INTEGER, ALLOCATABLE :: EDGE_IMPACT_ZONE(:,:)
        
        
        INTEGER :: PATCH_NUM
        INTEGER :: NEWINDEX, RECENT_INDEX, TEMP
        
        INTEGER :: I, J, TYP
        
        INTEGER, ALLOCATABLE :: POINT_INDEX(:)
        INTEGER, ALLOCATABLE :: EDGE_INDEX(:)
        
        INTEGER, ALLOCATABLE :: PATCH_POINT_NUM(:), PATCH_EDGE_NUM(:)
        TYPE(SURFACE_TYPE), POINTER :: SURFACE_CURRENT
        
        IF (TYP==0) THEN
            SURFACE_CURRENT => SURFACE_FLUID
        END IF
        IF (TYP==1) THEN
            SURFACE_CURRENT => SURFACE_PROPEL
        END IF
        IF (TYP==2) THEN
            SURFACE_CURRENT => SURFACE_CASE
        END IF
        
        
        ALLOCATE(POINT_INDEX(SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(NEWPOINT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_VELOCITY(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_DISPLACEMENT(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_EDGE_CONNECTION(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_TYPE(SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_RELATEDPT(3,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_RELATEDEDGE(3,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_FORCE(2,SURFACE_CURRENT%SURFACE_POINTS_NUM))
        
        ALLOCATE(EDGE_INDEX(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(NEWEDGE(2,SURFACE_CURRENT%SURFACE_EDGES_NUM))        
        ALLOCATE(SURFACE_INITIAL_EDGE_LENGTH(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_B_RATE(SURFACE_CURRENT%SURFACE_EDGES_NUM))        
        ALLOCATE(EDGE_LOCATION(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_ONINTERFACE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_PRESSURE(SURFACE_CURRENT%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_IMPACT_ZONE(3,SURFACE_CURRENT%SURFACE_EDGES_NUM))
        
        ALLOCATE(PATCH_POINT_NUM(100))
        PATCH_POINT_NUM = 0
        TEMP = 0
	PATCH_NUM = 0
        DO WHILE(TEMP < SURFACE_CURRENT%SURFACE_POINTS_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,I))==PATCH_NUM) THEN
                    PATCH_POINT_NUM(PATCH_NUM) = PATCH_POINT_NUM(PATCH_NUM) + 1
                    TEMP = TEMP + 1
                END IF
            END DO
        END DO        
        
        
        PATCH_NUM = 0
        NEWINDEX = 0
        RECENT_INDEX = 0
	POINT_INDEX = 0
        DO WHILE(NEWINDEX < SURFACE_CURRENT%SURFACE_POINTS_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,I))==PATCH_NUM ) THEN
                    RECENT_INDEX = I
                    EXIT
                END IF
            END DO
            
            TEMP = 0
            DO WHILE(TEMP < PATCH_POINT_NUM(PATCH_NUM))
                IF(SURFACE_CURRENT%EDGE_LOCATION(SURFACE_CURRENT%POINT_EDGE_CONNECTION(1,RECENT_INDEX))==PATCH_NUM) THEN
                    TEMP = TEMP + 1
                    NEWINDEX = NEWINDEX + 1
                    NEWPOINT(:,NEWINDEX) = SURFACE_CURRENT%SURFACE_POINTS(:,RECENT_INDEX)
                    POINT_INDEX(RECENT_INDEX) = NEWINDEX
                    RECENT_INDEX = SURFACE_CURRENT%SURFACE_EDGES(2,SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,RECENT_INDEX))
                END IF
            END DO
        END DO
        
        SURFACE_CURRENT%SURFACE_POINTS = NEWPOINT

        ALLOCATE(PATCH_EDGE_NUM(100))
        PATCH_EDGE_NUM = 0
        TEMP = 0
	PATCH_NUM = 0
        DO WHILE(TEMP < SURFACE_CURRENT%SURFACE_EDGES_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(I)==PATCH_NUM) THEN
                    PATCH_EDGE_NUM(PATCH_NUM) = PATCH_EDGE_NUM(PATCH_NUM) + 1
                    TEMP = TEMP + 1
                END IF
            END DO
        END DO  
        
        PATCH_NUM = 0
        NEWINDEX = 0
        RECENT_INDEX = 0
	EDGE_INDEX = 0
        DO WHILE(NEWINDEX < SURFACE_CURRENT%SURFACE_EDGES_NUM)
            PATCH_NUM = PATCH_NUM + 1

            DO I = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
                IF(SURFACE_CURRENT%EDGE_LOCATION(I)==PATCH_NUM) THEN
                    RECENT_INDEX = I
                    EXIT
                END IF
            END DO
            
            TEMP = 0
            DO WHILE(TEMP < PATCH_EDGE_NUM(PATCH_NUM))
                IF(SURFACE_CURRENT%EDGE_LOCATION(RECENT_INDEX)==PATCH_NUM) THEN
                    TEMP = TEMP + 1
                    NEWINDEX = NEWINDEX + 1
                    NEWEDGE(:,NEWINDEX) = SURFACE_CURRENT%SURFACE_EDGES(:,RECENT_INDEX)
                    EDGE_INDEX(RECENT_INDEX) = NEWINDEX
                    RECENT_INDEX = SURFACE_CURRENT%POINT_EDGE_CONNECTION(2,SURFACE_CURRENT%SURFACE_EDGES(2,RECENT_INDEX))
                END IF
            END DO
        END DO
        
        
        DO I = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            POINT_VELOCITY(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_VELOCITY(:,I)
            POINT_DISPLACEMENT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_DISPLACEMENT(:,I)
            POINT_EDGE_CONNECTION(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,I)
            POINT_TYPE(POINT_INDEX(I)) = SURFACE_CURRENT%POINT_TYPE(I)
            POINT_RELATEDPT(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDPT(:,I)
            POINT_RELATEDEDGE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_RELATEDEDGE(:,I)
            POINT_FORCE(:,POINT_INDEX(I)) = SURFACE_CURRENT%POINT_FORCE(:,I)
        END DO
        
        SURFACE_CURRENT%POINT_EDGE_CONNECTION = POINT_EDGE_CONNECTION
        DO J = 1, SURFACE_CURRENT%SURFACE_POINTS_NUM
            POINT_EDGE_CONNECTION(:,J) = EDGE_INDEX(SURFACE_CURRENT%POINT_EDGE_CONNECTION(:,J))
        END DO        
        
        DO J = 1, SURFACE_CURRENT%SURFACE_EDGES_NUM
	    NEWEDGE(:, EDGE_INDEX(J)) = POINT_INDEX(SURFACE_CURRENT%SURFACE_EDGES(:,J))
            SURFACE_INITIAL_EDGE_LENGTH(EDGE_INDEX(J)) = SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH(J)
            EDGE_B_RATE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_B_RATE(J)
            EDGE_LOCATION(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_LOCATION(J)
            EDGE_ONINTERFACE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_ONINTERFACE(J)
            EDGE_PRESSURE(EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_PRESSURE(J)
            EDGE_IMPACT_ZONE(:,EDGE_INDEX(J)) = SURFACE_CURRENT%EDGE_IMPACT_ZONE(:,J)
        END DO
        
        SURFACE_CURRENT%POINT_VELOCITY = POINT_VELOCITY
        SURFACE_CURRENT%POINT_DISPLACEMENT = POINT_DISPLACEMENT
        SURFACE_CURRENT%POINT_EDGE_CONNECTION = POINT_EDGE_CONNECTION
        SURFACE_CURRENT%POINT_TYPE = POINT_TYPE
        SURFACE_CURRENT%POINT_RELATEDPT = POINT_RELATEDPT
        SURFACE_CURRENT%POINT_RELATEDEDGE = POINT_RELATEDEDGE
        SURFACE_CURRENT%POINT_FORCE = POINT_FORCE

        SURFACE_CURRENT%SURFACE_INITIAL_EDGE_LENGTH = SURFACE_INITIAL_EDGE_LENGTH
        SURFACE_CURRENT%EDGE_B_RATE = EDGE_B_RATE
        SURFACE_CURRENT%EDGE_LOCATION = EDGE_LOCATION
        SURFACE_CURRENT%EDGE_ONINTERFACE = EDGE_ONINTERFACE
        SURFACE_CURRENT%EDGE_PRESSURE = EDGE_PRESSURE
        SURFACE_CURRENT%EDGE_IMPACT_ZONE = EDGE_IMPACT_ZONE
        
        DEALLOCATE(POINT_INDEX)
        DEALLOCATE(NEWPOINT)
        
        DEALLOCATE(POINT_VELOCITY)
        DEALLOCATE(POINT_DISPLACEMENT)
        DEALLOCATE(POINT_EDGE_CONNECTION)
        DEALLOCATE(POINT_TYPE)
        DEALLOCATE(POINT_RELATEDPT)
        DEALLOCATE(POINT_RELATEDEDGE)
        DEALLOCATE(POINT_FORCE)
        
        DEALLOCATE(EDGE_INDEX)
        DEALLOCATE(NEWEDGE) 
        
        DEALLOCATE(SURFACE_INITIAL_EDGE_LENGTH)
        DEALLOCATE(EDGE_B_RATE)
        DEALLOCATE(EDGE_LOCATION)
        DEALLOCATE(EDGE_ONINTERFACE)
        DEALLOCATE(EDGE_PRESSURE)
        DEALLOCATE(EDGE_IMPACT_ZONE)
        
        DEALLOCATE(PATCH_POINT_NUM)
        DEALLOCATE(PATCH_EDGE_NUM)

    END SUBROUTINE



    SUBROUTINE REARRANGE_PROPEL_INDEX(POINT_NUM, POINT, EDGE_NUM, EDGE, EDGE_LOCATION)
        IMPLICIT NONE
        REAL(8), DIMENSION(:,:) :: POINT(:,:)
        INTEGER, DIMENSION(:,:) :: EDGE(:,:)
	INTEGER, DIMENSION(:) :: EDGE_LOCATION(:)
        
        REAL(8), ALLOCATABLE :: NEWPOINT(:,:)

        
        REAL(8), ALLOCATABLE :: SURFACE_INITIAL_EDGE_LENGTH(:)
        REAL(8), ALLOCATABLE :: EDGE_B_RATE(:)
        REAL(8), ALLOCATABLE :: POINT_VELOCITY(:,:)
        REAL(8), ALLOCATABLE :: POINT_DISPLACEMENT(:,:)
        INTEGER, ALLOCATABLE :: POINT_EDGE_CONNECTION(:,:)
        INTEGER, ALLOCATABLE :: POINT_TYPE(:)
        
        INTEGER, ALLOCATABLE :: EDGE_ONINTERFACE(:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDPT(:,:)
        INTEGER, ALLOCATABLE :: POINT_RELATEDEDGE(:,:)
        REAL(8), ALLOCATABLE :: EDGE_PRESSURE(:)
        REAL(8), ALLOCATABLE :: POINT_FORCE(:,:)
        INTEGER, ALLOCATABLE :: EDGE_IMPACT_ZONE(:,:)
        INTEGER, ALLOCATABLE :: CONNECTION(:,:)
        
        
        INTEGER :: PATCH_NUM
        INTEGER :: RECENT_INDEX, TEMP, temp1
	real(8) :: L, LMIN
        
        INTEGER :: I, J, POINT_NUM, EDGE_NUM, OLD_INDEX
        
        INTEGER, ALLOCATABLE :: POINT_INDEX(:)
        INTEGER, ALLOCATABLE :: EDGE_INDEX(:)
        
        INTEGER, ALLOCATABLE :: PATCH_POINT_NUM(:), PATCH_EDGE_NUM(:)

        allocate(connection(2,edge_num))
        DO I=1,EDGE_NUM
            CONNECTION(2,EDGE(1,I)) = I
            CONNECTION(1,EDGE(2,I)) = I
        END DO
        
        ALLOCATE(PATCH_POINT_NUM(100))
        PATCH_POINT_NUM = 0
        TEMP = 0
        PATCH_NUM = 0
        DO WHILE(TEMP < POINT_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, POINT_NUM
                IF(EDGE_LOCATION(CONNECTION(1,I))==PATCH_NUM) THEN
                    PATCH_POINT_NUM(PATCH_NUM) = PATCH_POINT_NUM(PATCH_NUM) + 1
                    TEMP = TEMP + 1
                END IF
            END DO
        END DO        
        
        
        PATCH_NUM = 0
        RECENT_INDEX = 0
	allocate(point_index(point_num))
        POINT_INDEX = 0
	TEMP = 0
	temp1 = 0
        DO WHILE(TEMP1 < POINT_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, POINT_NUM
                IF(EDGE_LOCATION(CONNECTION(1,I))==PATCH_NUM ) THEN
                    RECENT_INDEX = I
                    EXIT
                END IF
            END DO
            LMIN = 100.
            DO I = 1, SURFACE_PROPEL%SURFACE_POINTS_NUM
                L = SQRT(DOT_PRODUCT(POINT(:,RECENT_INDEX)-SURFACE_PROPEL%SURFACE_POINTS(:,I),POINT(:,RECENT_INDEX)-SURFACE_PROPEL%SURFACE_POINTS(:,I)))
                IF(L<LMIN) THEN
		    LMIN = L
                    OLD_INDEX = I
                    POINT_INDEX(OLD_INDEX) = RECENT_INDEX 
                END IF
            END DO  
	    temp1 = temp1 + 1       
            
            TEMP = 1
            DO WHILE(TEMP < PATCH_POINT_NUM(PATCH_NUM))
                TEMP = TEMP + 1
		temp1 = temp1 + 1
                RECENT_INDEX = EDGE(2,CONNECTION(2,RECENT_INDEX))
                OLD_INDEX = SURFACE_PROPEL%POINT_EDGE_CONNECTION(2,SURFACE_PROPEL%SURFACE_EDGES(2,OLD_INDEX))
                POINT_INDEX(OLD_INDEX) = RECENT_INDEX 
            END DO
        END DO
        

        ALLOCATE(PATCH_EDGE_NUM(100))
        PATCH_EDGE_NUM = 0
        TEMP = 0
        PATCH_NUM = 0
        DO WHILE(TEMP < EDGE_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, EDGE_NUM
                IF(EDGE_LOCATION(I)==PATCH_NUM) THEN
                    PATCH_EDGE_NUM(PATCH_NUM) = PATCH_EDGE_NUM(PATCH_NUM) + 1
                    TEMP = TEMP + 1
                END IF
            END DO
        END DO  
        
        PATCH_NUM = 0
        RECENT_INDEX = 0
	allocate(edge_index(edge_num))
        EDGE_INDEX = 0
	temp = 0
	temp1 = 0
        DO WHILE(TEMP1 < EDGE_NUM)
            PATCH_NUM = PATCH_NUM + 1
            DO I = 1, EDGE_NUM
                IF(EDGE_LOCATION(I)==PATCH_NUM) THEN
                    RECENT_INDEX = I
                    EXIT
                END IF
            END DO
            
            DO I = 1, SURFACE_PROPEL%SURFACE_POINTS_NUM
                IF(EDGE(1,RECENT_INDEX) == POINT_INDEX(I)) THEN
                    OLD_INDEX = SURFACE_PROPEL%POINT_EDGE_CONNECTION(2,I)
                    EDGE_INDEX(OLD_INDEX) = RECENT_INDEX 
		    temp1 = temp1 + 1
                    EXIT
                END IF
            END DO
            
            TEMP = 1
            DO WHILE(TEMP < PATCH_EDGE_NUM(PATCH_NUM))
                TEMP = TEMP + 1
		temp1 = temp1 + 1
                RECENT_INDEX = CONNECTION(2,EDGE(2,RECENT_INDEX))
                OLD_INDEX = SURFACE_PROPEL%POINT_EDGE_CONNECTION(2,SURFACE_PROPEL%SURFACE_EDGES(2,OLD_INDEX))
                EDGE_INDEX(OLD_INDEX) = RECENT_INDEX
            END DO
        END DO
        
        ALLOCATE(POINT_VELOCITY(2,SURFACE_PROPEL%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_DISPLACEMENT(2,SURFACE_PROPEL%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_EDGE_CONNECTION(2,SURFACE_PROPEL%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_TYPE(SURFACE_PROPEL%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_RELATEDPT(3,SURFACE_PROPEL%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_RELATEDEDGE(3,SURFACE_PROPEL%SURFACE_POINTS_NUM))
        ALLOCATE(POINT_FORCE(2,SURFACE_PROPEL%SURFACE_POINTS_NUM))
        
        DO I = 1, SURFACE_PROPEL%SURFACE_POINTS_NUM
            POINT_VELOCITY(:,POINT_INDEX(I)) = SURFACE_PROPEL%POINT_VELOCITY(:,I)
            POINT_DISPLACEMENT(:,POINT_INDEX(I)) = SURFACE_PROPEL%POINT_DISPLACEMENT(:,I)
            POINT_EDGE_CONNECTION(:,POINT_INDEX(I)) = SURFACE_PROPEL%POINT_EDGE_CONNECTION(:,I)
            POINT_TYPE(POINT_INDEX(I)) = SURFACE_PROPEL%POINT_TYPE(I)
            POINT_RELATEDPT(:,POINT_INDEX(I)) = SURFACE_PROPEL%POINT_RELATEDPT(:,I)
            POINT_RELATEDEDGE(:,POINT_INDEX(I)) = SURFACE_PROPEL%POINT_RELATEDEDGE(:,I)
            POINT_FORCE(:,POINT_INDEX(I)) = SURFACE_PROPEL%POINT_FORCE(:,I)
        END DO

        
        ALLOCATE(SURFACE_INITIAL_EDGE_LENGTH(SURFACE_PROPEL%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_B_RATE(SURFACE_PROPEL%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_ONINTERFACE(SURFACE_PROPEL%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_PRESSURE(SURFACE_PROPEL%SURFACE_EDGES_NUM))
        ALLOCATE(EDGE_IMPACT_ZONE(3,SURFACE_PROPEL%SURFACE_EDGES_NUM))
        
        DO J = 1, SURFACE_PROPEL%SURFACE_EDGES_NUM
            SURFACE_INITIAL_EDGE_LENGTH(EDGE_INDEX(J)) = SURFACE_PROPEL%SURFACE_INITIAL_EDGE_LENGTH(J)
            EDGE_B_RATE(EDGE_INDEX(J)) = SURFACE_PROPEL%EDGE_B_RATE(J)
            EDGE_ONINTERFACE(EDGE_INDEX(J)) = SURFACE_PROPEL%EDGE_ONINTERFACE(J)
            EDGE_PRESSURE(EDGE_INDEX(J)) = SURFACE_PROPEL%EDGE_PRESSURE(J)
            EDGE_IMPACT_ZONE(:,EDGE_INDEX(J)) = SURFACE_PROPEL%EDGE_IMPACT_ZONE(:,J)
        END DO
        
        SURFACE_PROPEL%SURFACE_POINTS = POINT
        SURFACE_PROPEL%POINT_VELOCITY = POINT_VELOCITY
        SURFACE_PROPEL%POINT_DISPLACEMENT = POINT_DISPLACEMENT
        SURFACE_PROPEL%POINT_EDGE_CONNECTION = CONNECTION
        SURFACE_PROPEL%POINT_TYPE = POINT_TYPE
        SURFACE_PROPEL%POINT_RELATEDPT = POINT_RELATEDPT
        SURFACE_PROPEL%POINT_RELATEDEDGE = POINT_RELATEDEDGE
        SURFACE_PROPEL%POINT_FORCE = POINT_FORCE
        
        
        SURFACE_PROPEL%SURFACE_EDGES = EDGE
        SURFACE_PROPEL%SURFACE_INITIAL_EDGE_LENGTH = SURFACE_INITIAL_EDGE_LENGTH
        SURFACE_PROPEL%EDGE_B_RATE = EDGE_B_RATE
        SURFACE_PROPEL%EDGE_LOCATION = EDGE_LOCATION
        SURFACE_PROPEL%EDGE_ONINTERFACE = EDGE_ONINTERFACE
        SURFACE_PROPEL%EDGE_PRESSURE = EDGE_PRESSURE
        SURFACE_PROPEL%EDGE_IMPACT_ZONE = EDGE_IMPACT_ZONE
        
        DEALLOCATE(POINT_INDEX)
        
        DEALLOCATE(POINT_VELOCITY)
        DEALLOCATE(POINT_DISPLACEMENT)
        DEALLOCATE(POINT_EDGE_CONNECTION)
        DEALLOCATE(POINT_TYPE)
        DEALLOCATE(POINT_RELATEDPT)
        DEALLOCATE(POINT_RELATEDEDGE)
        DEALLOCATE(POINT_FORCE)
        
        DEALLOCATE(EDGE_INDEX)
        
        DEALLOCATE(SURFACE_INITIAL_EDGE_LENGTH)
        DEALLOCATE(EDGE_B_RATE)
        DEALLOCATE(EDGE_ONINTERFACE)
        DEALLOCATE(EDGE_PRESSURE)
        DEALLOCATE(EDGE_IMPACT_ZONE)
        
        DEALLOCATE(PATCH_POINT_NUM)
        DEALLOCATE(PATCH_EDGE_NUM)
        DEALLOCATE(CONNECTION)

    END SUBROUTINE
END MODULE
